### ISSUE TITLE
launch issue

### ISSUE THREAD

**Issue by Firegamer56** [EinEinfach/CaSSAndRA#100]
Problem when starting "Start" via the site "http://grauonline.de" the robot no longer uses cassandra programming but that of the site

**Comment by EinEinfach** [comment]
Using two different apps is always problematic. It can work, but it doesn't have to. I have not tested such scenarios in the past and do not plan to do so in the future.

If you want to understand what there exactly happens. You habe to start with analyzing log entries (both Cassandra log and sunray fw log)
