### ISSUE TITLE
Chrome: Scollbars

### ISSUE THREAD

**Issue by disaster123** [EinEinfach/CaSSAndRA#11]
Hi,

on my Linux System i get horizontal scrollbars in chrome.

I could fix this by removing the margin-right or margin-left of the .row calss from the bootstrap.min.css. The issie seems that there are 100% width row + margin which extends 100%.

```
.row {
    --bs-gutter-x: 1.5rem;
    --bs-gutter-y: 0;
    display: flex;
    flex-wrap: wrap;
    margin-top: calc(-1 * var(--bs-gutter-y));
>>>>    margin-right: calc(-.5 * var(--bs-gutter-x));
>>>>    margin-left: calc(-.5 * var(--bs-gutter-x));
}
```

Greets,
Stefan

**Comment by disaster123** [comment]
Screenshot:
![image](https://github.com/EinEinfach/CaSSAndRA/assets/861558/b5290f4c-4cb8-4af4-817c-9863854e8498)

**Comment by Frischid** [comment]
I tried to address this issue in #1, if I remember correctly is was due to a missing container which is required for a proper bootstrap layout. I can try to make a minimal PR for this on Saturday.

**Comment by disaster123** [comment]
Danke! funktioniert
