### ISSUE TITLE
http request timeout

### ISSUE THREAD

**Issue by goosst** [EinEinfach/CaSSAndRA#112]
Hello

Thanks a lot for the great software, it really makes life easier :).
I do have a suggestion for more robustness:

When trying to make a map, I often went off-line with the robot (and takes every time a long time to get back on-line). 
When pinging to the robot I sometimes had spikes going to 3000 ms.
So I checked the code and found a timeout was set to 2 seconds in CaSSAndRA/src/backend/comm/connections.py: 

class HTTP: 
`res = requests.post(url=self.http_ip, headers=self.header, data=data+'\n', timeout=2)`
etc.

If I changed all the timeouts in that class to 6 seconds, my issue of constantly going off-line was resolved and mapping goes much smoother :).
I think it could be a future improvement to also make this timeout a parameter through the frontend (or increase the default value).

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/daea61ee8d7ec90f08868b8b54f9fb85be14674c
