### ISSUE TITLE
Way Calculation Effekt

### ISSUE THREAD

**Issue by duemchen** [EinEinfach/CaSSAndRA#114]
getestet mit Version 99.2 (Ist aber ein alter Effekt.)
In einem Winkelbereich wird die eine Richtungsberechnung ca. um den KoordinatenNullpunkt rausgedreht.
Ich habe square benutzt, um gleich beides zu zeigen. Einzeln aber identische Ergebnis.
die andere Richtung teils ok, teils fehlgeschlagen.
Anbei auch die Karten .cassandra

Die Winkel von oben nach unten in Grad : 12ok, 13f, 36f, 40f, 41fok
Unten die MAP mit Koordinate 00 links unten

![12ok_12grd](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/a6676058-5e3a-4554-9d3c-10c15deadb0d)
![13effekt_13grd](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/cd049aa2-5f15-4b71-bcfd-afe5ff85eccd)
![36effekt_36grd](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/81454c46-aeb9-4c62-8dc7-4598add2d8c4)
![40effekt_40grd](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/61c53265-bebb-441f-a16e-df9ff5f2308c)
![41ok_41grd](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/e674eafb-d91c-469c-8852-f794cd6d2617)
![map_Nullpunkt](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/100c7f4f-61f7-4e0b-a5c8-89fbd47740fc)
[.cassandra.zip](https://github.com/EinEinfach/CaSSAndRA/files/14328455/default.cassandra.zip)

**Comment by EinEinfach** [comment]
Ich hatte einige user, die das Problem haben. Ich kann es nicht nachstellen. Kannst du mal die Version aus dem dem tur-figure-test branch testen, leider habe ich von keinem feedback bekommen, ob damit geht oder nicht.

https://github.com/EinEinfach/CaSSAndRA/issues/98

**Comment by duemchen** [comment]
Getestet mit turn-figure-tests
Geht! Prima.

**Comment by duemchen** [comment]
Versehentlich geschlossen!

**Comment by EinEinfach** [comment]
Ok, dann überlege ich mir, wie ich das in dem Master Zweig unterbringen kann. Danke für das Feedback

**Comment by EinEinfach** [comment]
Ist im master branch enthalten
https://github.com/EinEinfach/CaSSAndRA/commit/0b4dbd64675a38211e99d304e86b66e2f8951d67
bitte testen

**Comment by duemchen** [comment]
Getestet. Effekt war auf Raspi3 aufgetreten. Fehler ist behoben. 
Effekt lässt sich nicht mehr nachstellen. 
Danke!

Übrigens konnte ich mit gleichen Kartendaten und 99.2 auf einem anderen Rechner (Laptop Ubuntu) den Effekt nicht nachstellen. 

Zusatzfrage: Funktioniert die Abschaltung Mowexclusion? Rein optisch sieht die Karte nicht so aus.
Mowexclusion=false in Settings und in Main.

![mowsettings](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/6769fb24-91bb-46b2-a548-96b0fe166496)
![map_ohne_Mow exclusion border](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/ba085622-193b-4d34-9305-59446b1e9f4d)

**Comment by EinEinfach** [comment]
Doch das geht. Bei deinem Beispiel ist speziell das Problem, deine Karte ist zu schmall und der Mower  muss irgendwie nach ganz links und zurück und da fährt er an der Exclusion entlang. Wenn du das nicht möchtest, kannst du versuchen einen virtuellen Suchdraht zwischen Exclusion und Perimeter reinzulegen (zu finden in der Mapping section)

**Comment by duemchen** [comment]
Wenn Du's sagst. Hier eine ganz einfache Karte ohne Engstelle. Sieht für mich genauso aus. 
Ich teste es denmächst draussen! 

Danke. Suchdraht ist übrigens tolle Erweiterung!

![EinfachRandAus](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/0f47566c-90ad-4850-ad69-1722dd1ce5d2)
![einfachSettings](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/90cf8729-c84b-4595-82b4-857a39ff318c)

**Comment by EinEinfach** [comment]
Anhand dieser Karte verstehe ich nicht dein Problem. Anscheinend reden wir an einander vorbei

**Comment by duemchen** [comment]
Hier nochmal besser sichtbar, was ich meinte: 
ExlusionBorder off, aber 4 BorderLaps.
Ich hätte erwartet, dass Rand und Borderlaps nicht gefahren werden. 
"Mow cut edge exclusion: [on, off]. Should exclusions and border to be mowed" lt. Beschreibung.

![einfachRandaus_4BorderLaps](https://github.com/EinEinfach/CaSSAndRA/assets/13303693/978b1cdd-9e4a-473b-8518-5032e6e52b47)

**Comment by EinEinfach** [comment]
Nein, das verstehst du falsch. Exclusionen befinden sich innerhalb des Perimeters. Und da deine Karte keine Exclusionen hat, wirkt sich diese Einstellung nichts aus.

**Comment by duemchen** [comment]
In Cassandras Git Readme steht es im Abschnitt Coverage path planner
Aber Du hast Recht, Exclusions! Trotzdem finde ich meine Erwartung nicht so abwegig. Ich möchte manchmal einfach möglichst unfallfrei die Fläche mähen, ohne die Feinheiten der Ränder und Exclusions und die damit verbundenen "Gefahren".
Aber Schluß von WünschDirWas! Ich danke für Deine Geduld!
