### ISSUE TITLE
undocking clarification

### ISSUE THREAD

**Issue by goosst** [EinEinfach/CaSSAndRA#117]
Hello

At this point, I'm a bit lost how the entire undocking works i.e. which part belongs in Cassandra and which in the sunray firmware.
It's not clear to me what the criteria are to let the robot follow the dock path defined in Cassandra (but in the reverse direction to leave its house).

- If I just navigate the robot to its "house" and ask it to mow, he just rotates in his house and goes to some point in the mowing field (if I lift up his house).
- If the robot is charging in his house (cassandra flags docked) and ask it to mow, it just beeps two times and that's it.

Since other people on forum were confused about rotation in the house I had played with this part of the software to make sure it's not linked to the number of docking points etc. . But no improvement.
![image](https://github.com/EinEinfach/CaSSAndRA/assets/8907127/61f3ae01-83e2-447c-851e-4b9961264360)

I'm probably again missing something obvious. (I have a gps fix etc. when the robot is in its house.)

![image](https://github.com/EinEinfach/CaSSAndRA/assets/8907127/11a1b288-dff0-421e-aa87-4332757aefb3)

**Comment by EinEinfach** [comment]
How did you record your dock path? The last point is always charging station. If you create it in opposite direction then it leads to this behavior

**Comment by goosst** [comment]
yes, it was recorded in the correct direction. 
for clarity: docking works (follows the path to its house), undocking is the part which I didn't get to work yet.

**Comment by EinEinfach** [comment]
You have to check the serial monitor output of the sunray fw during undock session.

**Comment by goosst** [comment]
leaving the docking station properly seems to work when the robot is charging, if not charging it doesn't follow the path.
