### ISSUE TITLE
Joystick ball not at mouse/touch position if using Dockerfile

### ISSUE THREAD

**Issue by greymfm** [EinEinfach/CaSSAndRA#121]
I'm trying out lastest code (Github master with provided docker), and it seems the Joystick ball is never at the mouse/touch position  (same on all Ubuntu web browsers and Android phone web browsers I tested, Chrome, Firefox etc.)...

What could be the issue? :-)  Any previous version I could try? 

![image](https://github.com/EinEinfach/CaSSAndRA/assets/11735886/45a14d2a-fb08-417d-b487-b13875d0aa77)

**Comment by hjw2015** [comment]
+1 - same here since the last updates.

**Comment by EinEinfach** [comment]
Did you do that:

"Copy the dash_daq.min.js file from the repository you cloned into the dash_daq libraries folder and replace the existing file"

**Comment by greymfm** [comment]
OK, shouldn't the docker-script do this? ;-)  Let me try to add this to the docker script...

**Comment by EinEinfach** [comment]
"OK, shouldn't the docker-script do this? ;-) Let me try to add this to the docker script..."

For sure! Without It won't be worked. The legacy library is unfortunately bugged

**Comment by greymfm** [comment]
I can it working with a local Conda-based Python installation, however this does not seem to work with the docker file provided and the below added commands... (it replaces the .js file, but for some reason the browser reload still uses some other file...) 

```
# bugfix some Python library
##RUN mkdir -p /root/.local/lib/python3.10/site-packages/dash_daq
##COPY ./bugfix_dash_daq_min/dash_daq.min.js /root/.local/lib/python3.10/site-packages/dash_daq
COPY ./bugfix_dash_daq_min/dash_daq.min.js /root/.local/lib/python3.10/site-packages/dash_daq


```

**Comment by greymfm** [comment]
Sorry, it's working correctly if the line above was added - Let me know if you want me to make a  pull-request for this...

**Comment by greymfm** [comment]
It's for the Dockerfile provided in this project (as an easy starter). To make it universal, maybe we could apply the patch directly in the app.py ...

**Comment by ShadedSelf** [comment]
I dont know much about dockerfiles but it seems like it forces python 3.10.
https://github.com/EinEinfach/CaSSAndRA/blob/e1b96232de54cf5fddbad36bef6652ef991778a8/Dockerfile#L1

**Comment by ShadedSelf** [comment]
Also if we import the fixed JS file from the assets folder it should override the original function assuming it loads afterwards.
