### ISSUE TITLE
inactive save buttons

### ISSUE THREAD

**Issue by zoral566** [EinEinfach/CaSSAndRA#123]
I modified the docking route and the map a bit, but I can't save it.
![Screenshot 2024-04-30 14 44 08](https://github.com/EinEinfach/CaSSAndRA/assets/39862820/6c7a0813-0c3a-4ec3-b900-6915a43d4c81)

**Comment by zoral566** [comment]
[Screen recording 2024-04-30 16.02.20.webm](https://github.com/EinEinfach/CaSSAndRA/assets/39862820/40267ce8-d864-43f8-91ac-310371e16891)
Maybe the error is in my head :)

**Comment by EinEinfach** [comment]
For some reason after clicking move points your made changes has been reseted to legacy. It cold happened if your shapes aren't valid. Try it again and pls log everything in debug level.

**Comment by zoral566** [comment]
> For some reason after clicking move points your made changes has been reseted to legacy. It cold happened if your shapes aren't valid. Try it again and pls log everything in debug level.

[2024-04-30 17 02 20 INFO Backend  Starting backend.txt](https://github.com/EinEinfach/CaSSAndRA/files/15166768/2024-04-30.17.02.20.INFO.Backend.Starting.backend.txt)

**Comment by zoral566** [comment]
> Some shape is intersecting itself
> 
> 2024-04-30 17:03:08 DEBUG TopologyException: Input geom 1 is invalid: Self-intersection at 5.618942576603521 16.17930306185232

unfortunately, this is the same problem when moving any point on the map. I exported from Sunray.

**Comment by EinEinfach** [comment]
Your import is already faulty, you have to fix this coordinates before you can use it. Just check the coordinates mentioned above

**Comment by zoral566** [comment]
> 16.1793

I looked for the point in question in the .json file, deleted it, everything is OK. Thank you very much.

**Comment by EinEinfach** [comment]
"16.1793

I looked for the point in question in the .json file, deleted it, everything is OK. Thank you very much." 

It was written by you, didn't? I thought it is everything alright

**Comment by zoral566** [comment]
> "16.1793
> 
> I looked for the point in question in the .json file, deleted it, everything is OK. Thank you very much."
> 
> It was written by you, didn't? I thought it is everything alright

yes, I retaliated. I deleted all 16.17 entries, after pressing the button on the right, it lets me save, but the old map is saved. I'll map again tomorrow.

**Comment by EinEinfach** [comment]
Log? I think it is another issue

**Comment by EinEinfach** [comment]
Don't use the same name for new map, in this case your changes will be ignored without warnings. Still on to do list...

**Comment by zoral566** [comment]
[map (1).json](https://github.com/EinEinfach/CaSSAndRA/files/15175379/map.1.json)
[2024 05 01 10 43 32 INFO.txt](https://github.com/EinEinfach/CaSSAndRA/files/15175436/2024.05.01.10.43.32.INFO.txt)
The attached sunray file does not have the incorrect position. What to do? THX

**Comment by EinEinfach** [comment]
Can you attach here your sunray export. I will check that

**Comment by EinEinfach** [comment]
Ah sorry, didn't see the map json before

**Comment by EinEinfach** [comment]
![image](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/7cc896c3-489f-4ebd-92b2-7365c28a6089)
Here, just remove this point by marking it an clicking "-" after that is your map valid

**Comment by EinEinfach** [comment]
![Bildschirmfoto vom 2024-05-01 14-34-09](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/abd681fd-c4d3-4647-b084-8a1938d2e44f)
That is the self intersection.

**Comment by zoral566** [comment]
I was able to delete it in the sunray application, and downloaded it again. Now it works perfectly. Thank you very much. :)

> ![Bildschirmfoto vom 2024-05-01 14-34-09](https://private-user-images.githubusercontent.com/26028367/327123073-abd681fd-c4d3-4647-b084-8a1938d2e44f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Njk2ODAsIm5iZiI6MTcxNDU2OTM4MCwicGF0aCI6Ii8yNjAyODM2Ny8zMjcxMjMwNzMtYWJkNjgxZmQtYzRkMy00NjQ3LWIwODQtOGExOTM4ZDJlNDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEzMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDRmNDkzMjUwNWQ0ODFmNmUxMzQ5YjMzZDEyYWRiMjIyMzlhNmI0ZWMwM2YzMzE0ZDYzMjRhZmQxMWI0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPy-1AzcMCENL9o2Msr3fQYpI86E-th_mkut5PCRRKc) That is the self intersection.

I was able to delete it in the sunray application, and downloaded it again. Now it works perfectly. Thank you very much. :)
