### ISSUE TITLE
Sunray firmware HTTP protocol changes

### ISSUE THREAD

**Issue by greymfm** [EinEinfach/CaSSAndRA#13]
In der aktuellen Sunray-Master-Firmware (Development) gibt es eine Ergänzung zum HTTP-Protokoll - man muss hierfür die Datei "src/backend/data/datatodf.py" ergänzen:

![Screenshot from 2023-07-12 18-01-25](https://github.com/EinEinfach/CaSSAndRA/assets/11735886/53960f6b-3aaf-482e-bb42-f15ca6331020)

**Comment by EinEinfach** [comment]
Ah ok, ich fixe das. Danke

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/298ab254842d86586b0ff40830605b2ee918ba98
