### ISSUE TITLE
MQTT API: Battery as absolute value

### ISSUE THREAD

**Issue by marvin78** [EinEinfach/CaSSAndRA#131]
I would like to use absolute value of battery charge status (eg. 29,6V). The percentage is useless on Alfred because you cannot balance it between charging and mowing. Because of that Alfred is almost never "charging" but always "docked". 100% in dock is not 100% while mowing. So the absolute value is important to see which state we have during charging in dock.

**Comment by EinEinfach** [comment]
Sorry but don't understand what you mean with absolute value

**Comment by marvin78** [comment]
![Screenshot_20240513-210839](https://github.com/EinEinfach/CaSSAndRA/assets/10920356/75806bec-4653-41bf-8ef2-e13d0d3d24cd)

**Comment by marvin78** [comment]
Auf Deutsch: bei Alfred ist der Prozentwert nutzlos, wenn gedockt. Das BMS kann nicht ausreichend amgezapft werden. Anhand der Voltzahl kann man aber auslesen, wie weit geladen ist. Auch wenn die Zahlen nicht stimmen, ergeben sie so wenigstens Sinn. Im Dock hat Alfred eigentlich immer 100% wenn man die Werte in den Settings so angegeben hat, sodass sie beim Mähen Sinn ergeben.

**Comment by EinEinfach** [comment]
Also willst du eine Spannungsschwelle ab wann zwischen Charging und Docked entschieden werden soll?

**Comment by marvin78** [comment]
Nein. Ich brauche nur die markierten Werte über die MQTT Api.

**Comment by EinEinfach** [comment]
Ok, das sind Werte vom Roboter. Ich kann die dir direkt durchrouten, wenn es dir hilft und du dir nicht vom Roboter abgreifen willst. Geht schnell, mache ich morgen

**Comment by marvin78** [comment]
Danke :)

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/f5cf53fb5e396d9deed3cd698927d64a286a0f94

**Comment by marvin78** [comment]
Danke!
