### ISSUE TITLE
Taskplanner: Lasso Punkte hinzufügen/entfernen und Lasso im Task speichern

### ISSUE THREAD

**Issue by themanfrommoon** [EinEinfach/CaSSAndRA#133]
Moin,

ich versuche mich gerade an den ersten Tasks und arbeite dabei mit dem Lassowerkzeug.
Nun habe ich mir einige Gedanken gemacht, wie ich diese Exklusionen am besten anfahren möchte.
Ich hatte zuerst ein Lasso mit 8 Punkten, die ich dann nahe auf die Eckpunkte gesetzt habe:
![grafik](https://github.com/EinEinfach/CaSSAndRA/assets/28815063/03830a69-2797-46be-adcd-de2c8ef9b50f)
Jetzt habe ich aber eine bessere Idee, und möchte mit 16 Lassopunkten die Anfahrt möglichst in einer Linie machen, damit nicht "in die Exklusion" reingedreht werden muss.
Dazu müsste ich das Lasso editieren können Punkte hinzufügen/entfernen und verschieben.

Es wäre also sehr hilfreich, wenn das Lasso mit im Task gespeichert wäre, um es nachträglich verändern zu können.

Vielen Dank und beste Grüße,
Chris

**Comment by EinEinfach** [comment]
Nein das geht nicht out of the box. Hierzu muss ich zu viel am Framework ändern. Kosten nutzen steht für mich nicht in einem annehmbaren Verhältnis.
