### ISSUE TITLE
API MQTT

### ISSUE THREAD

**Issue by zoral566** [EinEinfach/CaSSAndRA#137]
`    - name: "switch.dennamow"
      command_topic: "CaSSAndRA/api_cmd"
      payload_on: "{\"robot\":{\"command\": \"mow\", \"value\": [\"all\"]}}"
      qos: 0
      retain: false`

works fine

`    - name: "switch.dennahome"
      command_topic: "CaSSAndRA/api_cmd"
      payload_on: "{\"robot\":{\"command\": \"start\"}}"
      qos: 0
      retain: false`

start, stop, dock don t working.
"4. Stopp:
{"robot":{"command": "stop"}}
5. Dock:
{"robot":{"command": "dock"}} "

Am I making a mistake, or does the start, stop, home command not work? Thanks

**Comment by EinEinfach** [comment]
start isn't valid command.

Stop and dock, I need Cassandra log output in debug level

**Comment by zoral566** [comment]
CaSSAndRA/api_cmd {"robot":{"command": "stop"}}
CaSSAndRA/robot {"status": "mow", "dockReason": null, "battery": {"soc": 100, "voltage": 31.62, "electricCurrent": 2.36}, "position": {"x": 1.23, "y": 0.5}, "target": {"x": 1.32, "y": 0.57}}
CaSSAndRA/maps {"loaded": "home_", "available": ["home", "home_", "homex", "h"]}
CaSSAndRA/tasks {"selected": [], "loaded": [], "available": []}
CaSSAndRA/mow parameters {"pattern": "lines", "width": 0.15, "angle": null, "distancetoborder": 2, "mowarea": true, "mowborder": 0, "mowexclusion": true, "mowborderccw": true}
CaSSAndRA/map {"mowprogressIdxPercent": 0, "mowprogressDistancePercent": 0}
CaSSAndRA/status busy
CaSSAndRA/status ready
CaSSAndRA/robot {"status": "mow", "dockReason": null, "battery": {"soc": 100, "voltage": 31.61, "electricCurrent": 2.52}, "position": {"x": 1.52, "y": 0.55}, "target": {"x": 2.19, "y": 0.52}}
CaSSAndRA/maps {"loaded": "home_", "available": ["home", "home_", "homex", "h"]}
CaSSAndRA/tasks {"selected": [], "loaded": [], "available": []}
CaSSAndRA/mow parameters {"pattern": "lines", "width": 0.15, "angle": null, "distancetoborder": 2, "mowarea": true, "mowborder": 0, "mowexclusion": true, "mowborderccw": true}
CaSSAndRA/map {"mowprogressIdxPercent": 0, "mowprogressDistancePercent": 0}
CaSSAndRA/status ready
CaSSAndRA/robot {"status": "mow", "dockReason": null, "battery": {"soc": 100, "voltage": 31.62, "electricCurrent": 2.57}, "position": {"x": 1.76, "y": 0.59}, "target": {"x": 2.19, "y": 0.52}}
CaSSAndRA/maps {"loaded": "home_", "available": ["home", "home_", "homex", "h"]}
CaSSAndRA/tasks {"selected": [], "loaded": [], "available": []}
[debug.txt](https://github.com/EinEinfach/CaSSAndRA/files/15355535/debug.txt)

**Comment by EinEinfach** [comment]
I already fixed that tomorrow or today later the update will be available

**Comment by zoral566** [comment]
Thank you for your work.

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/90549a20a3f4f9a95319bb8b07ba15f33f7df1fe

**Comment by marvin78** [comment]
> start isn't valid command.
> 
> Stop and dock, I need Cassandra log output in debug level

I have an additional question. Is there a way to resume over the API?

**Comment by EinEinfach** [comment]
{"robot":{"command": "mow", "value": ["resume"]}

**Comment by marvin78** [comment]
Ah. Super. Danke!
