### ISSUE TITLE
Add new map

### ISSUE THREAD

**Issue by zoral566** [EinEinfach/CaSSAndRA#138]
is it possible to add a new map? I'm trying to add a new separate section, but it disappears when I press the + button.
[Screen recording 2024-05-17 21.35.57.webm](https://github.com/EinEinfach/CaSSAndRA/assets/39862820/8fa2576e-78f4-4715-aa49-3afb84d75d22)

**Comment by EinEinfach** [comment]
It is not allowed to have two perimeter areas. You have to create a separate map in map selection dropdown.

**Comment by zoral566** [comment]
OK, Thank you.

**Comment by zoral566** [comment]
wouldn't it be possible to add a new terrain even just by merging a narrow strip? I try to add 2 new maps in vain, they cannot be combined. if I manually edit and pull out the map, I try to add the current position of the robot, but it is not possible because it no longer shows the robot position at the next point. THX
