### ISSUE TITLE
Fehler "Mow Area"

### ISSUE THREAD

**Issue by themanfrommoon** [EinEinfach/CaSSAndRA#144]
Moin,

Im Modus "Pattern: rings" hat das ausschalten von "Mow area" keinen Effekt.
Trotz ausgeschaltetem "Mow area" wird die gesamte Fläche gemäht:
![grafik](https://github.com/EinEinfach/CaSSAndRA/assets/28815063/0795ce2e-9287-48b2-bb9e-1f58ee3b6493)
![grafik](https://github.com/EinEinfach/CaSSAndRA/assets/28815063/71f94e9b-5b79-4ed8-b2b7-a251dea6ae82)

Im Modus "Pattern: lines" ist es korrekt:
![grafik](https://github.com/EinEinfach/CaSSAndRA/assets/28815063/11064e08-16d2-48b0-98a4-42f785ff7745)

Vielleicht kann man da ja nochmal nachbessern?

Vielen Dank und beste Grüße,
Chris

**Comment by EinEinfach** [comment]
Ist schon in der aktuellen Version behoben
