### ISSUE TITLE
Current version shows wrong mower icon

### ISSUE THREAD

**Issue by marvin78** [EinEinfach/CaSSAndRA#155]
Even though alfred ist selected, ardumower icon is shown on the map in the merged version. 

EDIT: I have to correct. Not ardumower is shown but default.

**Comment by EinEinfach** [comment]
How does your /usr/appcfg.json look like?

**Comment by marvin78** [comment]
That did not change after the update:

```
{
    "datamaxage": 10,
    "time_to_offline": 60,
    "voltage_to_soc": [
        {
            "V": 25.5,
            "SoC": 0
        },
        {
            "V": 29,
            "SoC": 100
        }
    ],
    "current_thd_charge": -0.03,
    "rover_picture": "alfred/",
    "obstacles_amount": 0,
    "light_mode": true,
    "rover_picture_size": 100
}
```

I made another instance for testing with cassandra_native and there it looks the same.

**Comment by marvin78** [comment]
No error in the log. BUT after the third reboot (of the rover, not Cassandra) the correct symbol is back).
