### ISSUE TITLE
Optimize pathplanner

### ISSUE THREAD

**Issue by EinEinfach** [EinEinfach/CaSSAndRA#16]
![1689319222144](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/f9fbc5fb-31b2-458c-b44a-1bd48b4cceae)
das Problem bei erster Karte:
- Pathplanner stellt fest, ich komme auf direktem Wege nicht mehr weiter
- Suche den nächstmöglichen Perimeterpunkt und starte A* Pathfinder und leider der Perimeterpunikt der am nähsten ist nun mal wo der blauer Pfad anfängt.
Bei der zweiten Karte, er will eigentlich diese Mähbahn mähen:
![1689322513361](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/16db97a0-c462-433b-8416-53ea2ec194c6)
Kommt aber aus rechten Ecke nicht direkt hin. Deswegen fängt er an entlang des Perimeters zu fahren. Der Weg ist zu Exclusion ist kürzer, als wenn er die ganze Zeit am Perimeter entlang fahren würde. Das könnte man lösen in dem man dem Pathfinder noch ein paar mögliche Wege vom Perimeterpunkt zum Perimeterpunkt beibring, würde die Ladezeit bei dem Umschalten der Karte erhöhen, wenn alle einverstanden sind, kann ich das einbauen, dann würde er von der Perimeterecke direkt zu Mähbahn fahren

**Comment by ShadedSelf** [comment]
Couldnt the pathfinder use a "virtual perimeter" that is offset by some value, like the edge mowing rings, so you can avoid going in and out of perimter/exclusions?

**Comment by EinEinfach** [comment]
Ich denke, ich habe es. Lösung für die zweite Karte. Einfach eine Notiz für mich, damit ich es nicht vergesse:
1. Es ist kein direkter Weg zum Zielpunkt möglich
2. Erstelle eine Kopie vom nx.Graph
3. Erweitere nx.Graph um zusätzliche Flanken in dem man jeden Weg vom route[-1] zu perimeter_points überprüft und im Falle within(perimeter) füge es dem nx.Graph zu
4. Mache das gleiche mit dem Zielpunkt
5. Lasse den A* pathfinder einen Weg suchen

**Comment by EinEinfach** [comment]
> Couldnt the pathfinder use a "virtual perimeter" that is offset by some value, like the edge mowing rings, so you can avoid going in and out of perimeter/exclusions?

For simple maps it could be a solution, but for more complex maps a offset of perimeter could cause a Multipolygon figure, what not so easy to handle

**Comment by EinEinfach** [comment]
Die beiden Probleme aus dem ersten Post müssten behoben sein
