### ISSUE TITLE
Deleting Maps does not work 

### ISSUE THREAD

**Issue by marvin78** [EinEinfach/CaSSAndRA#18]
If you try to delete a map you get nothing. Map is not deleted. The log says

`2023-07-15 20:36:22 ERROR Backend: Could not remove perimeter data from file
2023-07-15 20:36:22 DEBUG remove_task() missing 1 required positional argument: 'map_name'`

**Comment by EinEinfach** [comment]
Ok, thank you. I think there a small bug, what has to be removed. As workaround for now, create a simple task for this map, then try again

**Comment by marvin78** [comment]
It has multiple task in it.

**Comment by marvin78** [comment]
I tested the following: Removed all tasks from that map, delete does not work. Added a new small task and deletion is not working also.

**Comment by EinEinfach** [comment]
I found the bug, is nothing complicated, but I don't have time at the moment. I'll try to fix it soon

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/1b28a655b9b43eb160dcc701f9385cd3fd967740

**Comment by marvin78** [comment]
Thanks. Works fine
