### ISSUE TITLE
Use of cassandra

### ISSUE THREAD

**Issue by Firegamer56** [EinEinfach/CaSSAndRA#25]
I have just installed CaSSandRA on a server and would like more information

-Backup of connection parameters that skip.
-Possibility of programming the start-up.
-https access with authentication.
-Translation into several interface languages

**Comment by EinEinfach** [comment]
-Backup of connection parameters that skip.
Don't know what you exactly mean

-Possibility of programming the start-up.
Don't know what you exactly mean

-https access with authentication.
Cassandra runs on a machine in your local network, I don't see advantages to switch to https

-Translation into several interface languages
Yes, maybe in near future

**Comment by Firegamer56** [comment]
-Backup of connection parameters that skip.
I have a connection problem with alfred but it doesn’t seem to come from saving parameters

-Possibility of programming the start-up.
to have the possibility as on sunray to program alfred’s start times

-https access with authentication.
I would like to open Cassandra to the outside in order to see where alfred is at a distance

**Comment by Firegamer56** [comment]
I can no longer connect to alfred with Cassandra:
Here is the error => 

INFO Backend: Try initial HTTP request
juil. 23 21:01:12 raspberry python3[999]: 2023-07-23 21:01:12 DEBUG Calced checksumme: 0x16
juil. 23 21:01:12 raspberry python3[999]: 2023-07-23 21:01:12 DEBUG Data to be send: AT+V,0x16
juil. 23 21:01:12 raspberry python3[999]: 2023-07-23 21:01:12 WARNING Backend: HTTP-Connection to the rover lost or not possible. Trying to reconnect
juil. 23 21:01:12 raspberry python3[999]: 2023-07-23 21:01:12 DEBUG Invalid URL '192.168.1.28': No scheme supplied. Perhaps you meant https://192.168.1.28?
juil. 23 21:01:13 raspberry python3[999]: 2023-07-23 21:01:13 INFO Backend: Try initial HTTP request
juil. 23 21:01:13 raspberry python3[999]: 2023-07-23 21:01:13 DEBUG Calced checksumme: 0x16
juil. 23 21:01:13 raspberry python3[999]: 2023-07-23 21:01:13 DEBUG Data to be send: AT+V,0x16
juil. 23 21:01:13 raspberry python3[999]: 2023-07-23 21:01:13 WARNING Backend: HTTP-Connection to the rover lost or not possible. Trying to reconnect
juil. 23 21:01:13 raspberry python3[999]: 2023-07-23 21:01:13 DEBUG Invalid URL '192.168.1.28': No scheme supplied. Perhaps you meant https://192.168.1.28?

**Comment by EinEinfach** [comment]
Did it ever work? Maybe http:// missing in front of the IP adress

**Comment by Firegamer56** [comment]
Thanks a lot for moving it, I didn’t see it falait to enter the ip with http://

**Comment by EinEinfach** [comment]
-Possibility of programming the start-up.
to have the possibility as on sunray to program alfred’s start times
It's on to do list

-https access with authentication.
I would like to open Cassandra to the outside in order to see where alfred is at a distance
Maybe using a vpn server a way to reach your target

**Comment by Firegamer56** [comment]
Super thanks for the answers, I already use a vpn or else I nat port 80 on my box for access from outside

**Comment by Firegamer56** [comment]
I have the impression of an incompatibility between sunray and CaSSAndRA, it runs in circles when both the controls

**Comment by EinEinfach** [comment]
What is exactly the problem?

**Comment by Firegamer56** [comment]
He was stuck in one place and turned on himself, I cut it and he left

**Comment by EinEinfach** [comment]
Sounds like a problem from somewhere else. Actually there shouldn't be a problem in using both Applications on same time. Just check your position mode settings in sunray app and Cassandra app. It must be equal

**Comment by Firegamer56** [comment]
It is well in relative position on sunray and cassandra

**Comment by Firegamer56** [comment]
![image](https://github.com/EinEinfach/CaSSAndRA/assets/42047308/ec850b50-1aae-405f-9869-3e7943b4e509)

**Comment by EinEinfach** [comment]
Place is reserved for other stuff what I'm planning to do

**Comment by Firegamer56** [comment]
Do you think adding authentication is complicated?

**Comment by Firegamer56** [comment]
Hello, alfred is in programming with alexandra for mapping and the suddenly he tries to reach the antenna, the point of origin.

**Comment by EinEinfach** [comment]
Can't help you without additional informations... cassandras log and/or sunray fw log might be helpful

**Comment by Firegamer56** [comment]
Can you tell me she logs want you

**Comment by EinEinfach** [comment]
Standard log, like before at the moment where it happens

**Comment by Firegamer56** [comment]
not obvious log files are long

**Comment by Firegamer56** [comment]
where’s his logs from cassandra?

**Comment by EinEinfach** [comment]
It depends... if you are using Cassandra as a daemon service, you can access log entries via journalctl.
"journalctl -u cassandra -e"

**Comment by Firegamer56** [comment]
Is there a private place where you send the log file?

**Comment by Firegamer56** [comment]
I just tried again and when I program with will always break the same crash and so back with sunray

**Comment by Firegamer56** [comment]
I don’t want to publish the logs in public, do you have a security area?

**Comment by EinEinfach** [comment]
You can send me a private message on Ardumower Forum
