### ISSUE TITLE
Preload task doesn't load coordinates to the robot

### ISSUE THREAD

**Issue by EinEinfach** [EinEinfach/CaSSAndRA#26]
Preload button in taskplanner creates just an overview of lines. After pressing start button robot does his old task.

-> Preload button schould trigger Pathplanner and after that load new task to the robot

**Comment by disaster123** [comment]
Similar happens for the docking button if another map was used before. It does not trigger the upload of the current map.

**Comment by marvin78** [comment]
May be related to the issue with maps with different docks (i have a map with virtual dock). If you switch between maps, weird stuff might happen. Such as the previous map appears on the side of the cosen map and the mower tries to reach a point on the old map.

**Comment by EinEinfach** [comment]
> Similar happens for the docking button if another map was used before. It does not trigger the upload of the current map.

After switching map, dock button doesn't work?

**Comment by disaster123** [comment]
> > Similar happens for the docking button if another map was used before. It does not trigger the upload of the current map.
> 
> After switching map, dock button doesn't work?
> 
> #27

It works but starts docking for the old
Map.

**Comment by EinEinfach** [comment]
Ok, I created new issue for that

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/c6627fd4390fc2247c389f50ef10fa59f635f8e1
