### ISSUE TITLE
Switch map button should trigger map upload to the rover

### ISSUE THREAD

**Issue by EinEinfach** [EinEinfach/CaSSAndRA#27]
If map is switched -> take map command should be triggered

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commits?author=EinEinfach

**Comment by disaster123** [comment]
Irgendetwas ist da noch kaputt?

Bei mir passiert nun beim Kartenwechsel und einem Dockingversuch folgendes:

![image](https://github.com/EinEinfach/CaSSAndRA/assets/861558/360fa9f0-13e1-4592-b5c3-ef01507bd449)

**Comment by disaster123** [comment]
Ich kann den Bug aber nicht auf reopen setzen?

**Comment by disaster123** [comment]
Ich kann aktuell gar keine Karte mehr wechseln  er bleibt immer bei der alten Karte für die er berechnet

**Comment by disaster123** [comment]
mhm ich habe mal auf den latest master aktualisiert und meinen Browsercache geleert - nun scheint es zu gehen... sehr komisch
