### ISSUE TITLE
CaSSAndRA on alfred

### ISSUE THREAD

**Issue by disaster123** [EinEinfach/CaSSAndRA#3]
i wanted to try ~/CaSSAndRA on alfred. But the installatio of the requirements do not work.

```
pi@bananapi:~/CaSSAndRA $ pip3 install --user -r requirements.txt
Collecting dash==2.9.3 (from -r requirements.txt (line 1))

  Could not find a version that satisfies the requirement dash==2.9.3 (from -r requirements.txt (line 1)) (from versions: 0.17.4, 0.17.5, 0.17.7, 0.17.8rc1, 0.17.8rc2, 0.17.8rc3, 0.18.0, 0.18.1, 0.18.2, 0.18.3rc1, 0.18.3, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.22.0rc1, 0.22.0rc2, 0.22.0, 0.23.1, 0.24.0, 0.24.1rc1, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.26.0, 0.26.1rc1, 0.26.1rc2, 0.26.1rc3, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.26.5, 0.26.6, 0.27.0rc1, 0.27.0rc2, 0.27.0rc3, 0.27.0rc4, 0.27.0rc5, 0.27.0rc6, 0.27.0rc7, 0.27.0rc8, 0.27.0rc9, 0.27.0, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.28.5, 0.28.6, 0.28.7, 0.29.0rc1, 0.29.0rc2, 0.29.0rc3, 0.29.0rc4, 0.29.0rc5, 0.29.0rc6, 0.29rc7, 0.29.0rc8, 0.29.0, 0.30.0rc1, 0.30.0rc2, 0.30.0rc3, 0.30.0rc4, 0.30.0rc5, 0.30.0, 0.31.0rc1, 0.31.0rc2, 0.31.0, 0.31.1, 0.32.0rc1, 0.32.0rc2, 0.32.0, 0.32.1, 0.32.2, 0.34.0, 0.35.0rc1, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.36.0rc1, 0.36.0, 0.37.0rc1, 0.37.0rc2, 0.37.0, 0.38.0rc1, 0.38.0, 0.39.0, 0.40.0rc1, 0.40.0, 0.41.0, 0.42.0, 0.43.0rc1, 0.43.0rc2, 0.43.0rc3, 0.43.0, 1.0.0a1, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.13.4, 1.14.0, 1.15.0, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.18.0, 1.18.1, 1.19.0, 1.20.0, 1.21.0)
No matching distribution found for dash==2.9.3 (from -r requirements.txt (line 1))

```

Is this due to the fact that alfred comes with debian stretch running python 3.5 and isn't updateable...

Greets,
Stefan

**Comment by EinEinfach** [comment]
Maybe it's just enough to upgrade pip:
pip3 install --upgrade pip

**Comment by disaster123** [comment]
OK it's not - i checked the requirements and at least dash requires python 3.6. So i'm going to use a seperate linux machine for cassandra.

Is there any reason not to copy the dash fix min.js in the dockerfile?

**Comment by EinEinfach** [comment]
Dash fix have to be copied in any case. If you don't do that the remote control won't be work properly

**Comment by EinEinfach** [comment]
Python 3.6 is required for running dash==2.9.3

**Comment by Micka41** [comment]
Cassandra on Alfred is very slow, even at 1.4Ghz. The best solution is to use a device or a container (Proxmox, Docker, ...).

To get Python 10.9 or 10.10 on Alfred :
- You need to update Alfred sdcard to Buster : 
sudo nano /etc/apt/sources.list
=> buster

sudo nano /etc/apt/sources.list.d/raspi.list
=> buster

sudo apt update
sudo apt upgrade

sudo apt-get clean

sudo apt full-upgrade

sudo apt remove --purge "python2"
sudo apt autoremove --purge

Python 10 :

sudo apt install libssl-dev tk-dev libncurses5-dev libncursesw5-dev libdb5.3-dev libgdbm-dev libsqlite3-dev -dev liblzma-dev libffi-dev libgeos-dev libjpeg-dev

wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz
tar -zxvf Python-3.10.12.tgz

cd Python-3.10.12
./configure --enable-optimizations
sudo make altinstall

Good luck, it takes a long time
