### ISSUE TITLE
Sunray shows next mow point in map

### ISSUE THREAD

**Issue by disaster123** [EinEinfach/CaSSAndRA#30]
It would be great if CaSSAndRA can also show the next mow point in the map. Currently in only shows the next target point.

**Comment by EinEinfach** [comment]
Ok, shouldn't be a big problem. Any suggestions for form and/or color?

**Comment by EinEinfach** [comment]
Maybe change the current mowing line to dashed is also a way? Better understandable? In most cases rover target point is equal to mowing target point...

**Comment by disaster123** [comment]
Good idea I think those should be highlighted from the green. Like blue, orange, red or something. And yes it often the same but if it‘s  not it looks sometimes strange if you don’t know the real mowing point.

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/67c44af452651325d318012ad5bc363744a60c1c
