### ISSUE TITLE
Docking reason

### ISSUE THREAD

**Issue by disaster123** [EinEinfach/CaSSAndRA#31]
Would be great if CaSSAndRA can show the docking reason. Currently there are only dots below the word docking.

like: rain, battery empty, mowing finished,…

**Comment by EinEinfach** [comment]
Is this information available in sunray fw? I know as serial output string, but also in AT+S request?

**Comment by disaster123** [comment]
Ja ist im AT+S enthalten als stateSensor:
https://github.com/Ardumower/Sunray/blob/bdf9b1dd65303dd0c9ba18e60b1116a1648c10d5/sunray/comm.cpp#L587

**Comment by EinEinfach** [comment]
Das ist eine Größe, die ich nicht ganz verstehe. Wann geht die wieder auf no error? Undervoltage ist glaube ich nicht die Docking voltage. Finished steht dort auch nicht drin, also nur raining?

Ich müsste, dann eine gewisse Logik einbauen:
Wenn Docking und nicht finished und nicht raining -> Docking voltage reached

Bzw. Wie lange soll dann die Information bestehen bleiben? Bis zum nächsten Start, 1Std, nur während Docking?

**Comment by disaster123** [comment]
gute Frage wann die wieder auf no error geht ;-) ich glaube sobald die nächste Aktion gestartet wird... bzw. low voltage hast du aktuell recht - der Status wird aktuell nicht gesetzt - sind aber nur zwei Zeilen die dafür im sunray Code fehlen.

**Comment by EinEinfach** [comment]
Schlauer wäre es, wenn die Informationen von der Sunray fw zur Verfügung gestellt werden, wenn natürlich das nicht in Frage kommt, warum auch immer, könnte ich die Logik bauen

**Comment by disaster123** [comment]
Danke!

Leider läuft Cassandra bei mir nun nicht mehr. Ich tippe es liegt an den Task reworks.


```
cassandra    | 2023-08-24 08:16:09 INFO Backend: Starting server thread
cassandra    | 2023-08-24 08:16:09 INFO Backend: Backend is successfully started
cassandra    | 2023-08-24 08:16:11 INFO Backend: Performing get state http-request
cassandra    | 2023-08-24 08:16:11 DEBUG Calced checksumme: 0x13
cassandra    | 2023-08-24 08:16:11 DEBUG Data to be send: AT+S,0x13
cassandra    | 2023-08-24 08:16:11 DEBUG Starting new HTTP connection (1): 192.168.178.138:80
cassandra    | 2023-08-24 08:16:11 DEBUG http://192.168.178.138:80 "POST / HTTP/1.1" 200 86
cassandra    | 2023-08-24 08:16:11 DEBUG Status code: 200
cassandra    | 2023-08-24 08:16:11 DEBUG Content: S,30.99,0.34,0.41,0.08,2,2,0,0.86,0,-2.63,0.16,0.02,40,-0.00,31,15362,0.00,-1,0,0xf3
cassandra    | 
cassandra    | 2023-08-24 08:16:11 DEBUG Recieved checksum:0xf3 Calced checksum: 0xf3
cassandra    | Traceback (most recent call last):
cassandra    |   File "/usr/src/cassandra/app.py", line 79, in <module>
cassandra    |     main()
cassandra    |   File "/usr/src/cassandra/app.py", line 46, in main
cassandra    |     app = dash.Dash(
cassandra    |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 504, in __init__
cassandra    |     self.init_app()
cassandra    |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 588, in init_app
cassandra    |     self.enable_pages()
cassandra    |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 2041, in enable_pages
cassandra    |     self._import_layouts_from_pages()
cassandra    |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 2012, in _import_layouts_from_pages
cassandra    |     spec.loader.exec_module(page_module)
cassandra    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
cassandra    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cassandra    |   File "/usr/src/cassandra/src/pages/taskplanner.py", line 9, in <module>
cassandra    |     from src.components.tasks import map, buttongroupcontrol, modal, tasksorder
cassandra    |   File "/usr/src/cassandra/src/components/tasks/tasksorder.py", line 16, in <module>
cassandra    |     options=tasks.saved[tasks.saved['map name'] == current_map.name].name.unique()),
cassandra    |   File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
cassandra    |     indexer = self.columns.get_loc(key)
cassandra    |   File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
cassandra    |     raise KeyError(key)
cassandra    | KeyError: 'map name'
```

**Comment by EinEinfach** [comment]
I have a workaround for that, or wait until tomorrow, I'll fix that
[](https://forum.ardumower.de/threads/mein-projekt-cassandra-zur-steuerung-des-ardumowers.25120/post-62264)

**Comment by disaster123** [comment]
Da scheint noch ein Fehler zu sein. Er fuhr gerade wegen Regensensor zum Doxking aber als reason steht dort nun low battery.

**Comment by EinEinfach** [comment]
Ja die Logik ist noch fehlerhaft, schaue ich mir morgen an. Bzgl. des Fehler davor:
https://github.com/EinEinfach/CaSSAndRA/commit/fccae426b80767428ccfefae489263299890702a

**Comment by EinEinfach** [comment]
Hast du mal log von Cassandra zum Zeitpunkt?

**Comment by disaster123** [comment]
Das log ist so voll im debug mode... ich kann den Zeitraum so genau nicht eingrenzen...

**Comment by EinEinfach** [comment]
Schick alles, ich weiß nach was ich suchen soll

**Comment by disaster123** [comment]
Alles ist selbst mit gzip komprimiert noch 1,2MB logfile...

**Comment by EinEinfach** [comment]
Wie gesagt, ich weiß nach was ich suchen soll

**Comment by disaster123** [comment]
Hier ein gekürztes Log - weil es zu
[a.gz](https://github.com/EinEinfach/CaSSAndRA/files/12432721/a.gz)
fällig gerade wieder Regen gab. Diesmal steht in Cassandra aber korrekt: rain.

**Comment by EinEinfach** [comment]
Jetzt müsste es klappen
[https://github.com/EinEinfach/CaSSAndRA/commit/57a86382193e2a1c586bb0016f9276e074584258](url)
