### ISSUE TITLE
temp mow settings do not reset

### ISSUE THREAD

**Issue by disaster123** [EinEinfach/CaSSAndRA#32]
I would expect that the temp mow settings are getting reset at some point. Currently it seems they only get reset by reload the page. May be on map change? or after clicking mow calculation?

**Comment by EinEinfach** [comment]
But reset to what? "Temp mow setting" sounds wrong, maybe just rename to something else. I think remembering last changes is also ok, that are the settings for current page (state or tasks planner).

**Comment by disaster123** [comment]
I thought those are just for one mow calculation and then revert / reset to the defaults.

**Comment by EinEinfach** [comment]
The behavior of mow settings is now described in Readme. I think we can close this issue
