### ISSUE TITLE
TopologyException: Input geom 0 is invalid: Self-intersection

### ISSUE THREAD

**Issue by bavarialogy** [EinEinfach/CaSSAndRA#36]
Hi,

erst mal Tausend Dank für dieses Projekt, welches für mich als Cloud-Selber-Macher die letzte logische Brücke zur Unabhängigkeit meines Rasens bildet. Es ist erstaunlich, wie hier entwickelt wird und was in der Zeit dabei rausgekommen ist. Großartig!

Nun zum Problem: Ich habe eine Karte, die sämtlichen Good/Best Practices trotzt und einen recht ekelhaften Perimeter besitzt. In native Sunray funktioniert sie jedoch, weswegen ich auf eine komplette Neuerstellung gern verzichten würde.. Folglich wundert es mich aber auch nicht, dass ich beim Klick auf Mapping -> Use Selected Perimeter -> OK diese Exception bekomme:

`2023-08-10 20:21:24 ERROR Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/usr/src/cassandra/src/components/mapping/modal.py", line 143, in selected_perimeter
    current_map.create(selected_perimeter)
  File "/usr/src/cassandra/src/backend/data/mapdata.py", line 164, in create
    self.create_perimeter_polygon()
  File "/usr/src/cassandra/src/backend/data/mapdata.py", line 53, in create_perimeter_polygon
    perimeter = perimeter.difference(exclusions)
  File "/usr/local/lib/python3.10/site-packages/shapely/geometry/base.py", line 574, in difference
    return shapely.difference(self, other, grid_size=grid_size)
  File "/usr/local/lib/python3.10/site-packages/shapely/decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/shapely/set_operations.py", line 77, in difference
    return lib.difference(a, b, **kwargs)
shapely.errors.GEOSException: TopologyException: Input geom 0 is invalid: Self-intersection at 33.902622402674943 -12.654416049677573`

Mein Setup:
- docker-compose Stack, gebaut mit angepasstem Dockerfile vom aktuellem Stand (commit f1d611accc58369bdd1e3ed1efb988952ce488b2) 
- Debian x64
- relative Koordinaten

Ich würde gerne die Stelle finden, an der die Self-Intersection auftritt, bin aber zu inkompetent. Den Fehler ursächlich abfangen kann ich leider noch weniger. Was könnte ich tun, um die Stelle zu finden? Muss ich auf absolute Koordinaten umstellen, damit ich in einem GeoJSON Tool die Stelle vielleicht finden kann?

**Comment by EinEinfach** [comment]
Self intersection bedeutet du hast irgendwo eine Figur (exclusion oder perimeter) was sich selbst kreuzt (wie eine 8). Das magt Cassandra nicht. Eine Umstellung der Koordinaten ist nicht notwendig. Du könntest mir mal die Karte zur Verfügung stellen, ich schaue mal rein, wo diese Stelle ist und was man machen kann

**Comment by bavarialogy** [comment]
Danke für die Erläuterung, jetzt ergibt das Sinn. Derer Stellen gibt es auf meiner Karte leider einige.. --> https://pastebin.com/rdF3kV6x
Wenn ich wüsste, wie man GeoJSON ins Sunray-Format zurück konvertiert bekommt könnt ich's bestimmt auch selber probieren zu fixen. Im Sunray Editor will ich mir das nicht antun..

**Comment by EinEinfach** [comment]
Ich schaue mal rein, wird erst nächste Woche was. Ist etwas überraschend für mich, dass Sunray app das egal ist, muss ich mal schauen, ob ich sowas auch erlauben kann.

**Comment by EinEinfach** [comment]
Gibt es solche Stellen nur in den Exclusionen oder auch im Perimeter?

**Comment by bavarialogy** [comment]
Es gibt Exclusions, die übereinander liegen sowie mehrere Exclusions, die über dem Perimeter liegen. Als ich mir grade das GeoJSON auf geojson,io angeschaut habe ist mir aufgefallen, dass da eine gaanz feine Linie zu sehen ist, so als wäre da noch ein Punkt: 
![image](https://github.com/EinEinfach/CaSSAndRA/assets/75044179/cb188bf3-831f-4d9d-80f3-c92952644d33)

In diesem GeoJSON habe ich für die bessere Sichtbarkeit mal alle Exclusion Features entfernt, da ist das aufgefallen.

**Comment by bavarialogy** [comment]
Nachtrag: Mithilfe des in CaSSAndRA integrierten Map Editors konnte ich so weit reinzoomen, dass ich die zwei Stelle nun finden konnte. Da sind je zwei Perimeter Points über Kreuz geraten und es war ein minimaler Achter im Perimeter. Habe die entsprechenden Punkte einfach gegeneinander getauscht und voila, "use perimeter" funktioniert jetzt. Danke für die rasend schnelle Hilfe!
