### ISSUE TITLE
Use Selected Perimeter Modal Doesn't Dismiss

### ISSUE THREAD

**Issue by rothnic** [EinEinfach/CaSSAndRA#40]
When you click the button "Use Selected Perimeter", there is a modal that pops up. When you click "Ok", the modal doesn't dismiss and there is no additional feedback when clicking Ok.

I'd suggest just dismissing the modal at that point, or if there is no interaction needed, you could use a [toast](https://getbootstrap.com/docs/5.3/components/toasts/) instead. I think this could be used across the app where at the moment you don't get immediate feedback that clicking some of the buttons did something.

Another option, which might just be a misunderstanding of how to use the app, is typically when you click "Use Selected Perimeter", are you not wanting to then go to the main page of the app and actually use it? Should we take the person to that page at that time, or at least give them a button that takes them there?

**Comment by EinEinfach** [comment]
Yes it could take some time (depending on your machine) until selected perimeter is loaded. Some stuff is going on in background. I'll check if I can add a wait spinner or something else to give a feedback to user

**Comment by rothnic** [comment]
I've yet to see it ever dismiss, no matter how much time I give it. I'm running this in docker, so I've watched in the logs to see what is going on, and it just never seems to go away.

**Comment by EinEinfach** [comment]
Can you share Cassandra log when you clicked load selected perimeter

**Comment by rothnic** [comment]
I just updated to the latest changes in master and now it is going away for me. Still think that anytime you have an action that triggers something to happen on the server that might take some time that we should provide some feedback to the user that their action was received and is in progress (spinner, toast, etc), then trigger an error in the case it wasn't successful.

Going to close this ticket out since it is at least going away.
