### ISSUE TITLE
Handle sidewalks and driveway surfaces in map

### ISSUE THREAD

**Issue by rothnic** [EinEinfach/CaSSAndRA#41]
I have a couple small strips of grass that aren't connected to the rest of my lawn. Currently, both CaSSAndRA and the Sunray app require you to either mow those areas or to exclude them, while leaving a path to navigate through.

As I understand it now, the areas excluded from the interior of the map do not allow any kind of navigating through at the moment. The idea behind this change would be another type of area that isn't considered for mowing, but can be navigated through. Another option might be to support connecting two separate perimeters through a series of lines that are always used when moving between the two perimeters.

I think this isn't a super high priority, but it was something I came across and thought I'd capture it for future consideration.

Here is a picture of my perimeter map and a satellite view to see how I've had to deal with this issue at the moment. You can see I had to leave little pathways to these other areas, but the mower still creates mow patterns in these areas just used for access.

<img width="846" alt="image" src="https://github.com/EinEinfach/CaSSAndRA/assets/452052/b70a1e6b-47e7-46ac-b42a-2eb9c281c51f">
<img width="600" alt="image" src="https://github.com/EinEinfach/CaSSAndRA/assets/452052/eb71de76-81f2-4a9b-b777-1c2f15d0f6ae">

**Comment by EinEinfach** [comment]
Maybe creating tasks and combine they with each other will solve your problem. You can select your strips with defined mow settings and save it as a task 1, another area as a task2, don't select the ways between two areas. And last just select the saved tasks in drop-down menu in wanted mow order. Cassandra will connect automatically all selected areas without mowing ways between the areas.

**Comment by rothnic** [comment]
Gotcha, yeah the thing that is a little difficult handling it that way is it is sometimes hard to judge the actual area you need to select, but maybe I can figure something out like adding very small exclusions at the corners of the area I typically don't want to mow, so I can easy select only the area I do want to mow.
