### ISSUE TITLE
Simplify using docker and updating project

### ISSUE THREAD

**Issue by rothnic** [EinEinfach/CaSSAndRA#42]
I noticed in the readme it talks about needing to save off customized files and the data folder when updating the project. This could be made easier by separating the data files into their own folder and/or some gitignore updates. The current approach makes things difficult when updating the project when using Docker.

* At the very least, I think adding Dockerfile to the gitignore file would be an initial step
* Then I think it would be worth separating defaults from custom settings/data associated with a running app
* Finally, I think we could make it easier to use Docker by having a pre-built docker image. The dockerfile build suggestions are a bit on the complicated side and I don't think users need to be worried about the host user/group.

Here is the dockerfile that I used and seems to be working fine without as complicated of a build process. It likely could be simplified further, but the main thing is people shouldn't in most cases need to build their own image unless they are working on the project.

```
FROM python:3.10-slim
WORKDIR /usr/src/cassandra
COPY ./CaSSAndRA .
COPY ./requirements.txt /usr/src/cassandra
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["python3","app.py"]
```

That goes into the root of the git project directory, then you simply build the docker image like this:

`docker build . -t cassandra`

**Comment by EinEinfach** [comment]
I'm not familiar with docker, never used that. Also the description for docker installation is not written by me. If that really so simple, I can change that in readme.md

**Comment by rothnic** [comment]
An update on some progress on this. I have a branch where I'm using the Click python library that we already have as a dependency to parameterize the options when starting the server. I have also added a Dockerfile that can take those same options. I've handled all the hard-coded server options in command line parameters, then have a description that points to where the environment variables are defined that can also be used.

At the moment, the data_path is defined and is defaulting to the same relative location in the project, but haven't started leveraging it through the app yet, which is the next step. I'm wondering if we should default to a data location that is in the current users home directory.

So, when you start up the app for the first time, it would look for a folder like ~/.cassandra. If it doesn't exist, it is created. If the files required aren't there, then it creates the stubbed-out config files, then starts using them. Otherwise, it can take any other specific path you provide it.

Anyways, here is what it currently looks like with the changes to parameterize the server startup config settings:

```
(cassandra) Nicks-Macbook-Pro-4:CaSSAndRA nroth$ python app.py start --help
Usage: app.py start [OPTIONS]

  Start the CaSSAndRA Server

  Only some Dash server options are handled as command-line options. All other
  options should use environment variables. Find supported environment
  variables here: https://dash.plotly.com/reference#app.run

Options:
  -h, --host TEXT                 [default: 0.0.0.0]
  -p, --port INTEGER              [default: 8050]
  --data_path TEXT                [default: /Users/nroth/workspace/CaSSAndRA_d
                                  ev/CaSSAndRA/src/data]
  --proxy TEXT                    format={{input}}::{{output}} example=http://
                                  0.0.0.0:8050::https://my.domain.com
  --debug                         Enables debug mode for dash application
  --app_log_level [DEBUG|INFO|WARN|ERROR|CRITICAL]
                                  [default: DEBUG]
  --server_log_level [DEBUG|INFO|WARN|ERROR|CRITICAL]
                                  [default: ERROR]
  --pil_log_level [DEBUG|INFO|WARN|ERROR|CRITICAL]
                                  [default: WARN]
  --help                          Show this message and exit.
```

Then, if you want to use docker, the dockerfile will be in the repo, so you just do this: `docker build . -t cassandra`. Then, you can use it from the command line in the exact same way (you'll notice the only difference is the default data_path):

```
docker run -it cassandra start --help
Usage: app.py start [OPTIONS]

  Start the CaSSAndRA Server

  Only some Dash server options are handled as command-line options. All other
  options should use environment variables. Find supported environment
  variables here: https://dash.plotly.com/reference#app.run

Options:
  -h, --host TEXT                 [default: 0.0.0.0]
  -p, --port INTEGER              [default: 8050]
  --data_path TEXT                [default: /usr/src/cassandra/src/data]
  --proxy TEXT                    format={{input}}::{{output}} example=http://
                                  0.0.0.0:8050::https://my.domain.com
  --debug                         Enables debug mode for dash application
  --app_log_level [DEBUG|INFO|WARN|ERROR|CRITICAL]
                                  [default: DEBUG]
  --server_log_level [DEBUG|INFO|WARN|ERROR|CRITICAL]
                                  [default: ERROR]
  --pil_log_level [DEBUG|INFO|WARN|ERROR|CRITICAL]
                                  [default: WARN]
  --help                          Show this message and exit.
```

**Comment by rothnic** [comment]
@EinEinfach: I think I just about have all the configuration files handled. I have the app running from one folder and pulling configuration from `~/.cassandra`. Although I think this will be a bit more simple to manage in the app, it seems like another pass could be taken to further improve things a bit. However, this already seems like enough of an improvement to stop at. 

Some things I wanted to mention:
- Do you have any issues around the default path of `~/.cassandra` for storing data? This can always be overridden with any path via the `data_path` parameter
- I don't really understand the point of datacfg.json file. It seems to add a lot of complexity and there is still an assumption that this file and many other files are in a specific location relative to the app.
    - I've instead moved this into a simple object (namedtuple) that is instantiated with the parent directory being the config option I showed above (data_path). 
    - The backendserver.start() method is passed the data_path into it, which then shares the namedtuple of file directories with the other config classes/files
- I'm treating the /src/data files as initial data files and if missing, copying those into the data_path provided by the user. Otherwise, keeping the same directory structure.

I'll submit a pull request tomorrow when I have some time to clean this up and do some more testing. It looks like there have been some additional changes for logging that I'll need to handle, since it is also using local storage within the /src/data folder.

**Comment by EinEinfach** [comment]
> I don't really understand the point of datacfg.json file. It seems to add a lot of complexity and there is still an assumption that this file and many other files are in a specific location relative to the app.

The idea behind datacfg.json was at the beginning to have flexibility to move all data files  to other directory without code changes. Simple modify path inside of datacfg.json and done. I didn't know, do I need that or not, will the files stay on this place or not.

**Comment by rothnic** [comment]
@EinEinfach : see the pull request #70 

I need to update the readme file, but just running `python app.py` should explain the inputs pretty well. If you want to start the app with your current data folder you are using, you can copy the data folder to `~/.cassandra`. You can see how it looks for my folder here:

<img width="500" alt="image" src="https://github.com/EinEinfach/CaSSAndRA/assets/452052/45b4bf18-dd4d-44b8-9500-424b98f23f20">

What it is doing is using what is contained in `/src/data` as the initial files to copy to the `~/.cassandra` folder when the app first starts up, but only if they are missing. So, you can upgrade the app over and over without manually copying the `/src/data` folder around to avoid losing data.

> The idea behind datacfg.json was at the beginning to have flexibility to move all data files to other directory without code changes. Simple modify path inside of datacfg.json and done. I didn't know, do I need that or not, will the files stay on this place or not.

I think the thing I ran into with datacfg was that it is:
* assumed to be inside the application src folder
    * means that to change where the files are, we have to modify a tracked file in the git project, which makes modification difficult by end users
* being read over and over again so many times, but I think we can make the assumption for now that the file locations won't change without restarting the server
* there is a lot of duplicated code to read that file across files, so it makes it difficult to maintain
