### ISSUE TITLE
Some changes to moving points (german)

### ISSUE THREAD

**Issue by marvin78** [EinEinfach/CaSSAndRA#47]
Aus dem Forum (damit du es nicht vergisst ;)): 

Ich habe gerade mal das Verschieben von Punkten probiert. Erstmal Danke!!

2 Punkte würde ich mir dafür (erstmal noch) wünschen:

1. Wenn ich eine Linie verändere, in dem ich den Punkt verschiebe, wäre es sehr hilfreich, wenn die alte Linie und der alte Punkt als "Ghost" für den Zeitraum, in dem ich den Mausklick halte, zu sehen bleibt, damit man sehen kann, um wieviel man verschiebt. Ggf. kann auch die gesamte "alte" Karte bis zum Speichern sichtbar bleiben. In der original App ist das dadurch gewährleistet, dass man immer den Perimeter UND die Fahrspur hat, was ja hier nicht der Fall ist, da die Bahnen erst "live" berechnet werden. Damit kann man im Original genau sehen, was man verändert hat. Das ist beim Bearbeiten immer sehr hilfreich.
2. Das Grid müsste engmaschiger sein. Gerade wenn der Winkel nicht rechtwinklig ist, ist die Verschiebung der Punkte oft zu weit. Das ist mir schon beim Lasso aufgefallen, dass man da nicht genau genug arbeiten kann.

**Comment by EinEinfach** [comment]
You can test it now. Let me know if something is wrong!

**Comment by marvin78** [comment]
Thank you.

It is much better now. But it's a little awkward. Sometimes you move the mouse while holding a point and the cursor won't move, so you move further. Then, all of a sudden, the pointer moves a lot more than expected or wanted. It's very difficult to reach the target.

**Comment by EinEinfach** [comment]
In Desktop Mode?

**Comment by marvin78** [comment]
Yes.

**Comment by EinEinfach** [comment]
I need some more details. What exactly you clicked, expected behavior and what cassandra doing instead.

**Comment by marvin78** [comment]
Auf Deutsch:

Ich packe mir den Punkt, verschiebe ihn. Plötzlich stoppt der Punkt, während ich die Maus weiter bewege und dann stoppe, weil der Punkt nicht mehr da ist, wo ich mich hinbewegt habe. Etwas später und wenn ich wieder geht's dann weiter, ich bin aber mit der Maus schon ganz woanders, weit von dem Punkt weg, wo ich hin wollte. Man sieht die Bewegung nicht mehr, weil der Punkt kurz "einrastet". Ich weiß tatsächlich nicht, wie ich es anders beschreiben soll. Es erinnert ein wenig an die ersten Versuche mit einer Maus beim C64 ;). Noch nerviger ist, dass die Zoomstufe immer wieder springt. Aber das tut sie in allen Ansichten.

**Comment by EinEinfach** [comment]
Springt die Zoomstufe die ganze Zeit oder nur einmal nach Seitenwechsel?

**Comment by marvin78** [comment]
Seitenwechsel - man zoomt, es springt zurück. Soweit normal, das war "schon immer" so.

Aber nun ist es hier beim Mapping schon ein paar mal passiert, dass die Zoomstufe sprang, während man gerade einen Punkt gepackt hat. Das Verschieben bricht dann auch ab und der Punkt landet an der Stelle, an der man zuletzt war.

**Comment by EinEinfach** [comment]
Ich habe den Fehler gefunden. Ich musste auf das Hauptintervall umstellen, du  erinnerst dich, wegen nicht anzeigenden Seiten. Ich probiere gleich auf ein eigenes Intervall für die Mapping Seite umzustellen, dann musst du mal berichten, ob bei dir die Seite angezeigt wird.

**Comment by marvin78** [comment]
Ok. Ich teste, sobald du Bescheid sagst.

**Comment by marvin78** [comment]
Zoomstufe ist besser. Beim Verschieben noch immer das gleiche Bild. Ich hoffe, das Video wird genommen.


https://github.com/EinEinfach/CaSSAndRA/assets/10920356/67441150-5ced-472d-985b-9cd94bd1b774

**Comment by marvin78** [comment]
Ok. Jetzt nehme ich an, dass ich mit dem Neustart eben zu früh war oder der Neustart nicht erfolgt ist, denn ich sehe nun die Karte im Mapping wieder nicht mehr. Das Video oben muss dann noch auf der Version ohne eigenes Intervall entstanden sein. Mit eigenem Interval ist die Karte offenbar wieder nicht mehr sichtbar.

**Comment by EinEinfach** [comment]
Ich verstehe es nicht... was ist bei dir anders als bei mir... Und was steht in dem Browser als Fehler?

**Comment by marvin78** [comment]
`dash_renderer.v2_9_3m1688380819.min.js:2 ReferenceError: A nonexistent object was used in an `Input` of a Dash callback. The id of this object is `mapping-interval` and the property is `n_intervals`. The string ids in the current layout are: [interval, url-update, navbar-toggler, open_offcanvas, button-open-modal-info, navbar-collapse, offcanvas, linear-speed, angular-speed, joystick, speedsetpoint-offcanvas, button-slower, button-faster, button-fan, button-next-point, button-sunray-off, button-sunray-reboot, button-gps-reboot, modal-remotecontrol, modal-reomotecontrol-header, modal-remotecontrol-content, button-remotecontrol-ok, modal-info, modal-info-body, _pages_location, _pages_content, _pages_store, _pages_dummy, mapping-map, button-home-add, button-add-new-point, button-delete-last-point, button-move-points, button-cancel-map-action, button-perimeter-add, button-perimeter-diff, button-open-modal-choose-perimeter, modal-choose-perimeter, content-modal-choose-perimeter, button-open-modal-upload-file, modal-uplad-file, content-modal-upload-file, button-select-perimeter, button-add-new-perimeter, button-copy-perimeter, button-remove-perimeter, button-finish-figure, upload-sunray-file, button-save-imported-perimeter, modal-sunray-import, modal-sunray-import-title, modal-sunray-import-body, modal-overwrite-perimter, input-perimeter-name, ok-button-overwrite-perimeter, moadal-add-new-perimeter, ok-button-new-perimeter, modal-selected-perimeter, ok-button-selected-perimeter, modal-copy-perimeter, input-copy-perimeter, ok-button-copy-perimeter, modal-remove-perimeter, ok-button-remove-perimeter, modal-finish-mapping, input-new-perimeter, ok-button-finish-mapping, modal-no-fix-solution, ok-button-no-fix-solution, mapping-hidden, dropdown-sunray-import, dropdown-choose-perimeter]
    at Xa (dash_renderer.v2_9_3m1688380819.min.js:2:125450)
    at Qa (dash_renderer.v2_9_3m1688380819.min.js:2:125346)
    at cu (dash_renderer.v2_9_3m1688380819.min.js:2:129965)
    at dash_renderer.v2_9_3m1688380819.min.js:2:164602
    at pt (dash_renderer.v2_9_3m1688380819.min.js:2:41631)
    at dash_renderer.v2_9_3m1688380819.min.js:2:44600
    at dash_renderer.v2_9_3m1688380819.min.js:2:40819
    at e (dash_renderer.v2_9_3m1688380819.min.js:2:39619)
    at dash_renderer.v2_9_3m1688380819.min.js:2:164579
    at s (dash_renderer.v2_9_3m1688380819.min.js:2:156038)`

**Comment by EinEinfach** [comment]
Wenn du in deinem Cassandra Ordnder nach ids.MAPPINGINTERVAL suchst in welchen Dateien findest du da was

**Comment by marvin78** [comment]
Jau. 3 Dateien haben diesen Inhalt:

- \cassandra\src\components\mapping\map.py
- \cassandra\src\pages\mapping.py
- \cassandra\src\archive\components\mapping\map.py

**Comment by EinEinfach** [comment]
1. was ist mit app.py?
2. archive unterordner kenne ich nicht
3. in dem pages Ordner ist hoffentlich alles auskommentiert was mit ids.MAPPINGINTERVAL zu tun hat

**Comment by marvin78** [comment]
Sorry. archive ist mein Archivordner für alte Versionen. Bitte ignorieren. app.py habe ich nicht durchsucht, dort ist es aber auch vorhanden.

**Comment by marvin78** [comment]
Ich habe den  Fehler gefunden. Aus irgend einem Grund, war der Docker-Container, den ich verwende mit einer alten app.py unterwegs, obwohl die Datei eine neue war. Eigentlich ist mein Container so gebaut, dass er damit zurecht kommt, dass es Änderungen an den Dateien gibt. Im Grunde muss man die neuen Dateien nur rein werfen und Docker neu starten. Offenbar nimmt er aber die app.py nicht jedes Mal mit. Das muss ich mir anschauen. 

Ein Neu-Bauen des Containers bringt Abhilfe. 

Sorry, das was dann wohl hier eher mein Fehler. Ich teste nochmal das Punkte verschieben.

**Comment by marvin78** [comment]
Und was soll ich sagen? PERFEKT. Danke, so läuft das super und man kann mit den Punkten spielen, wie man möchte.

Daumen hoch!!

**Comment by EinEinfach** [comment]
Sehr gut, sonst hätte ich auch keine Ideen mehr

**Comment by marvin78** [comment]
Genau so nutze ich es. Ich weiß noch nicht, was da schief gelaufen ist. Aber das finde ich noch raus, wenn ich Zeit habe.
