### ISSUE TITLE
Allow pinch and zoom on mobile devices 

### ISSUE THREAD

**Issue by marvin78** [EinEinfach/CaSSAndRA#50]
It would be nice if this would work on maps on mobile devices.

**Comment by EinEinfach** [comment]
Sounds weird but this feature isn't supported by plotly. We have two options: 
- we find someone who can implement that in plotly 
- or we switch to other plot library, 
both of them is a lot of work. And I don't think we'll manage to do that.

Meanwhile you can try that: put your finger on one of the corners of the plot and move it up or down

**Comment by marvin78** [comment]
That works well. Not intuitive but it works. Thanks.
