### ISSUE TITLE
dbc.CardHead Information on state page

### ISSUE THREAD

**Issue by EinEinfach** [EinEinfach/CaSSAndRA#53]
Is this information necessary, or could be removed?
![photo1694414823-changed2](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/bda23727-b5af-4e74-a86d-fa37e41a4c4b)

**Comment by disaster123** [comment]
+1 for removal

**Comment by marvin78** [comment]
Can be removed

+1

**Comment by themanfrommoon** [comment]
Remove

+1
