### ISSUE TITLE
Fix view on small screens

### ISSUE THREAD

**Issue by EinEinfach** [EinEinfach/CaSSAndRA#54]
There is an issue on the bottom on small screens:

![photo1694434193-changed](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/562b8e41-01b1-401f-8270-a82b69e569eb)

The old version looks much better:

![photo1689336086(1)](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/7fa497c3-7142-4faa-933d-5596f560a1b6)

**Comment by ShadedSelf** [comment]
[Hmmm](https://webkit.org/blog/7929/designing-websites-for-iphone-x/),
I think you might need to add something like this for IOS:
`body {
    padding-bottom: env(safe-area-inset-bottom);
}`

But I cant test it

**Comment by EinEinfach** [comment]
Where exactly should I add this row?

**Comment by ShadedSelf** [comment]
style.css

**Comment by ShadedSelf** [comment]
Actually, maybe something like this its probably better:
`#_pages_content
{
    padding-bottom: env(safe-area-inset-bottom);
}`

**Comment by EinEinfach** [comment]
It doesn't work

**Comment by ShadedSelf** [comment]
Line 61 in app.py
` 'content': 'width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover' `

Im sure there is a way to make it work, if you are willing to take the time, google "env(safe-area-inset-bottom)" and "not working" or something like that, sadly I cant make the testing myself.
If not, set this to 34pixels or so.
`#_pages_content
{
    padding-bottom: 34px;
}`

**Comment by rothnic** [comment]
> Change line 61 in app.py to: `'content': 'width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover'`
> 
> Im sure there is a way to make it work, if you are willing to take the time, google "env(safe-area-inset-bottom)" and "not working" or something like that, sadly I cant make the testing myself. If not, set this to 34pixels or so. `#_pages_content { padding-bottom: 34px; }`

Yes, this is the same solution that I found as well. If you don't have the viewport-fit=cover, then the safe-area-inset-bottom doesn't work. With the viewport-fit=cover, it does apply the padding needed. Might have to find the right place to put that extra padding.

**Comment by rothnic** [comment]
<img width="1727" alt="image" src="https://github.com/EinEinfach/CaSSAndRA/assets/452052/0806db63-68fd-4fc7-ab74-61f546284214">

**Comment by rothnic** [comment]
> No, I can't see this problem on real device. All pages work as one page app

Ok, good. Then, yeah from my testing adding `viewport-fit=cover` and `#_pages_content { padding-bottom: env(safe-area-inset-bottom); }` as @ShadedSelf suggested, seems to work well. That style should take care of all pages when using the app in this add to home screen mode on iphone.

**Comment by rothnic** [comment]
> Thaks for help. It looks great again!

Glad we found the more correct solution vs adding padding to all devices. 

By the way, if you decide you want a little more or less padding, you can also use the `calc` function to adjust that a bit. For example, something like this `padding-bottom: max(0, calc(env(safe-area-inset-bottom) - 4px))` would adjust what ends up being a 34px padding to 30px without impacting other devices.

One other thing worth mentioning is that there are other `safe-area` variables we may need to revisit if we ever care about using a mobile device in landscape orientation, but at this point it doesn't seem super usable in that layout due to the other elements that constrain the plot too much.
