### ISSUE TITLE
now selection does not disappear after pressing start

### ISSUE THREAD

**Issue by disaster123** [EinEinfach/CaSSAndRA#58]
Currently  mow selection is still active after pressing play. This results in pan not working as it moves the selection instead of the map.

![image](https://github.com/EinEinfach/CaSSAndRA/assets/861558/e2c554c1-07ba-4f3f-ba4b-c10e550d2388)

**Comment by EinEinfach** [comment]
If box selection selected or lasso selection selected just double click on screen.

It is new feature. You can apply different mow settings to the same selection

**Comment by disaster123** [comment]
Does not work for me on iOS 16. A double tap does not result in anything. Please keep in mind that iOS does not support the double click event. You have to use a timer and single click event to detect double clicks on iOS.

But shouldn’t at least the play button clear the selection or Is there any use case to apply settings after pressing play?

**Comment by EinEinfach** [comment]
I also use iOS 16.6.1. Double click works fine for me. Make sure that boxselection is still selected in the tool bar

**Comment by disaster123** [comment]
Ah ok works fine so far. But may be play can still clear it?

**Comment by EinEinfach** [comment]
I mark this issue as feature request
