### ISSUE TITLE
Show map name

### ISSUE THREAD

**Issue by marvin78** [EinEinfach/CaSSAndRA#64]
Would it be possible to show the currently loaded map's name somewhere? I am always trying with different but very similar maps (little changes that cannot be spotted easily). I would like to know which map is the one that is currently loaded.

Reason: even if you don't actually change the garden, everything changes a tiny bit every day. Some routes on the perimeter work for month and then they don't. Small changes can help here. But it is always a little bit try and error. Therefore I need slightly different and changed maps.

**Comment by EinEinfach** [comment]
On the map page, or somewhere on state page?

**Comment by marvin78** [comment]
On all pages except Settings would be nice. Could be a very small text in the lower right corner of the coordinate system.

**Comment by EinEinfach** [comment]
You can test now

**Comment by marvin78** [comment]
Looks great :) Thank you.
