### ISSUE TITLE
Path in the wall

### ISSUE THREAD

**Issue by Micka41** [EinEinfach/CaSSAndRA#7]
Hello,

I've just seen a problem with the mowing path, it goes through an exclusion zone.

Cassandra 0.41

![Carte](https://github.com/EinEinfach/CaSSAndRA/assets/10485916/e7ca7420-1b29-4163-8c36-72261ca37c90)

![Screenshot_20230707-090525](https://github.com/EinEinfach/CaSSAndRA/assets/10485916/07e1f448-986f-475a-9500-d6b3ee46a481)

[map.txt](https://github.com/EinEinfach/CaSSAndRA/files/11979971/map.txt)

**Comment by EinEinfach** [comment]
I reproduced this failure, will take some days to fix that

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/a8e5b7606fc51a5afc51ba4a84b6a7eff58b206e
