### ISSUE TITLE
Automatically Build Docker Images

### ISSUE THREAD

**Issue by rothnic** [EinEinfach/CaSSAndRA#75]
The recent work that I committed in #70 was to separate config data from app src and to add a general-purpose Dockerfile. That new Dockerfile can be pre-built for anyone to use, so they don't have to checkout code, worry about migrating data between versions, etc. The only missing piece at this point is actually building the image.

## Background
- Docker hub is kind of the default image registry that you pull from when you run a command like `docker pull <image>`
- Docker hub used to support automatic building of docker images from github projects, but now that is done only for paid accounts
- However, Github does have an alternative now with their workflow actions
- Workflow actions are yml files stored within your github repository and outline specific steps to perform based on events occurring within your repository.

I have developed an initial workflow action within my fork of this repo to work through the steps required to get this working and I think I'm relatively close to a pull request. Here is what I needed to do:

## Setup Required

- **DockerHub**
  1. Create a dockerhub account if you don't already have one. Try leveraging the same username as your github one, because the username is typically part of the image name. This just keeps things simple to understand. I'd use lowercase `eineinfach`
  2. Create a repository in dockerhub that mirrors the github project. I used lowercase `cassandra`. See my repo here: [rothnic/cassandra](https://hub.docker.com/repository/docker/rothnic/cassandra/general)
  3. Go to your dockerhub profile, click "edit", then click "Security", then click "New Access Token". I gave my access token the name "Github" with read/write privileges. Leave this window open for now, or copy the token down locally.

- **Github**
  1. Go to this repository in github
  2. Click the Settings tab at the top
  3. Click Secrets and Variables on the left hand side, near the bottom
  4. Click "Actions" from the drop down
  5. Click New Repository Secret, give it the name `DOCKERHUB_USERNAME`, give it the value `eineinfach` (or whatever your username is for dockerhub), then save
  6. Add another secret with the name `DOCKERHUB_TOKEN`, give it the value copied from the previous DockerHub step 3. above

**Next Steps**
- Finalize workflow action file
  - I have added an initial github action to test, but I'm not 100% on it yet. There are a number of different variations I'm seeing and I created a branch to test that out. When I'm ready, I'm going to submit a pull request that will add a file in this repository in a special `.github/workflows` directory.
  - See current file [here](https://github.com/rothnic/CaSSAndRA/blob/build-docker-image/.github/workflows/docker-image.yml)
  - See the actions ran in my fork [here](https://github.com/rothnic/CaSSAndRA/actions)
- Merge pull request
- Docker builds will then occur automatically any time a push occurs to the repository
  - Currently, the file I committed will do that for each
    - commit (SHA added to end of  image name)
    - branch
    - tag (following a version format)
    - once a day at 10am
  - Not sure if all these make sense, but evaluating the setup

## Example

First image build: my branch where I'm developing this github action called [build-docker-image](https://hub.docker.com/layers/rothnic/cassandra/build-docker-image/images/sha256-3a84ddfcd60a28a50e26f85e33a38cd7c7fe37100ff8711a33be7e728e192d14?context=repo)

Previously, I would build my own image and run my docker image like this:
```
docker build . -t cassandra

docker run -it \
     -p 8050:8050 \
 -v /Users/nroth/.cassandra:/home/cassandra/.cassandra \
 -e TZ=US/Central \
 -e HOST_UID=$(id -u) \
 -e HOST_GID=$(id -g) \
 cassandra
```

Instead, you can just go directly to running the image, with the version at the end:
```
docker run -it \
     -p 8050:8050 \
 -v /Users/nroth/.cassandra:/home/cassandra/.cassandra \
 -e TZ=US/Central \
 -e HOST_UID=$(id -u) \
 -e HOST_GID=$(id -g) \
 rothnic/cassandra:build-docker-image
```

**Comment by EinEinfach** [comment]
Ok, I created DockerHub account and add new secrets in GitHub

**Comment by rothnic** [comment]
@EinEinfach you should have a pull request for this initial workflow version. We could now start tagging version releases, so docker will become what I think is the easiest way for non-developers to run cassandra.

For example, if we tag commit 1 as v1.2.3, then an image will exist built off commit 1, tagged as v1, v1.2, v1.2.3. Then, let's say we make a new commit 2 and tag that as v1.2.4. Then after building, the image v1 and v1.2 will point to commit 2. Then, there will also be a v1.2.4 image.

There will also be a "edge" tag, which will always point to the last commit on master, plus a tag for each branch, and pr. So, this should make it easy to test changes.

If we need to, we can always adjust this later. It'll be easy to see once we merge it, then we start getting some activity on the repository to build the images.

**Comment by EinEinfach** [comment]
Should I give a specific name convention to the commits? Or how is tagging exactly work?

**Comment by rothnic** [comment]
No need to do anything different for commits. Tags are handled after commit, where you point to a commit and give it a version in the format v*.*.*, which is the standard semver approach.

Even still, setting a version isn't required. It just helps for calling out specific releases we feel are stable. Without tags, the build file will still create a build per commit if someone wants to target a specific one.
