### ISSUE TITLE
Optimize connection settings

### ISSUE THREAD

**Issue by Novus4K** [EinEinfach/CaSSAndRA#76]
1. Show the currently configured connection settings by default.
2. If no connection settings are stored, do not attempt to establish a connection to the mower.
3. If no connection settings are stored, no entries about a lost connection should appear in the log.

**Comment by rothnic** [comment]
Yeah, this makes sense. It is confusing to open the settings area and you can't tell which if any are setup. It also does seem to get really angry in the logs when no configuration exists.

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/33486e8f953384fd2b68cb802517841e01b1ba23
