### ISSUE TITLE
Some styling findings

### ISSUE THREAD

**Issue by EinEinfach** [EinEinfach/CaSSAndRA#81]
![image](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/42006da9-ba64-431f-a829-e90057419852)

If I remember correctly before big styling update the stick wasn't cut. 

![image](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/afa1cfef-3f27-46dd-b011-b93abcc62569)

Also here the size of joystick is a little to big or container to small

**Comment by EinEinfach** [comment]
Here is one picture from old version 
![image](https://github.com/EinEinfach/CaSSAndRA/assets/26028367/ae983279-82db-4b1f-b34f-f660e42956cb)

**Comment by ShadedSelf** [comment]
The joystick and nipple cutting of comes from this css class:
`/* Dash adds tons of classless divs that we need to expand to the available space */
body, div:not([class]) {
  height:100%;
  overflow: hidden;
}`
Which removes overflow on empty divs.

This removes an empty div in joystick.py:
`joystick = Joystick(id=ids.JOYSTICK, size=230, angle=0, force=0)`

And this allows the nipple to overflow:
`.daq-joystick--light > div {
	overflow: visible !important;
}`

**Comment by ShadedSelf** [comment]
Oh, and this to prevent the scrollbar from appering when moving the joystick:
`.offcanvas-body
{
	overflow: hidden;
}`

**Comment by EinEinfach** [comment]
An idea how to fix?

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/pull/85
