### ISSUE TITLE
Adding the time function

### ISSUE THREAD

**Issue by Firegamer56** [EinEinfach/CaSSAndRA#82]
Is it possible to use the time line function ?

**Comment by EinEinfach** [comment]
You mean schedule?

**Comment by Firegamer56** [comment]
yes exactly

**Comment by Firegamer56** [comment]
When I mow with cassandra it does not stop anymore

**Comment by EinEinfach** [comment]
> yes exactly

It's next on to do list

**Comment by Firegamer56** [comment]
Great, I feel like he keeps the one sent by the site

**Comment by EinEinfach** [comment]
Check your DOCK_AUTO_START definition in config.h

**Comment by marvin78** [comment]
Wouldn't it be better to add possibility to use Cassandra with MQTT so you can do better things than mowing at a specific time (which could very well be bad for the lawn)? The daytime is not an important parameter to decide when mowing is to start. There are multiple parameters that should be used to decide when and where mowing has to start. Time is only a small part of that. 

The parameters that need to be fullfilled for a decision when and where to mow could only be handeld by a home automation software. So it would be nice if there was a possibility to get all information and to set all needed parameters by MQTT (choose Tasks and then go).

**Comment by EinEinfach** [comment]
It will be also possible at some point

**Comment by EinEinfach** [comment]
Schedule is available in last commit
