### ISSUE TITLE
finish and save after "move points" edit sometimes resets to old map

### ISSUE THREAD

**Issue by disaster123** [EinEinfach/CaSSAndRA#83]
Hi,

i was extensively using the move points function today. And pretty often (2 out of 10 times) finish and save resets to the old map and i've to redone the work.

**Comment by EinEinfach** [comment]
If you leaving "move points" mode? Or if you save changed map?

**Comment by disaster123** [comment]
If I try to save changed map - it sometimes resets to original map just before pressing save button

**Comment by EinEinfach** [comment]
But you left move points mode before save?

**Comment by disaster123** [comment]
Yes I did

**Comment by EinEinfach** [comment]
I don't know why but I will check that

**Comment by disaster123** [comment]
It looks like a race condition like it reloads the original map just before clicking save

**Comment by EinEinfach** [comment]
I activate interval update after leaving moving mode, maybe it comes faster then reshaping made changes

**Comment by EinEinfach** [comment]
I tried to locate the problem, but I didn't find any issues in logic behavior. Do you have a log file from your session?

**Comment by EinEinfach** [comment]
I have another idea why this could happen. If an invalid polygon is created during the point movement (e.g., lines crossing over each other), then the change is discarded and reverted to the original polygon. But this is not a bug.

**Comment by disaster123** [comment]
OK - i'm going to try to reproduce it and i'm going to close this issue right now. Thanks a lot!

**Comment by ShadedSelf** [comment]
Same here, the moment save and finish is clicked the perimeter goes back to the way it was.
It only works if there is no perimeter selected on the select map popup.

**Comment by EinEinfach** [comment]
With last commit it shouldn't be happen anymore

**Comment by ShadedSelf** [comment]
Im on master, log doesnt say anything either

**Comment by EinEinfach** [comment]
What do you exactly do?

**Comment by ShadedSelf** [comment]
- Go to mapping page
- Select a perimeter to be edited
- Add a shape/remove a shape/change a point, all of them show the same behaviour
- Click save and finish

While the popup to set a name is active you can see the perimeter reverting iteslf to how it was before the changes, if you dont do step 2 it works as expected.

**Comment by EinEinfach** [comment]
try now

**Comment by ShadedSelf** [comment]
Yup, seems fixed now.

**Comment by EinEinfach** [comment]
Some callbacks I'll never understand
