### ISSUE TITLE
Calculation Failure in new Coverage Planner (mowing are turned at 0,0 out of perimeter area)

### ISSUE THREAD

**Issue by SirVival71** [EinEinfach/CaSSAndRA#98]
With the current version of the mow coverage planner I have the problem that I get with "lines" a mowing area that is projected in the wrong place (see picture). It appears to be rotated beyond the 0 point to the perimeter and exclusion.
If I leave out the exclusion in the calculation, the mowing paths come correctly within the perimeter.
![image](https://github.com/EinEinfach/CaSSAndRA/assets/11841096/9301ba5e-8f65-4bdb-9749-d942cdf9d4e9)

Both still worked correctly with the old PathPlanner.

With "rings" it would even work correctly. With "squares":
![image](https://github.com/EinEinfach/CaSSAndRA/assets/11841096/d92724f9-aae8-4880-8ab2-69119f301fc9)

At/up to 99° MowAngle everything is still OK. At/from 100° it no longer works.

Issue exists e.g. with
{
"pattern": "lines",
"width": 0.18,
"angle": 134,
"distancetoborder": 1,
"mowarea": "yes",
"mowborder": 2,
"mowexclusion": "yes",
"mowborderccw": "yes"
}

**Comment by EinEinfach** [comment]
Oh yes, totally forgot about you!
At first make an update to the last verstion

**Comment by EinEinfach** [comment]
Do you have still the problem with  last version?

**Comment by SirVival71** [comment]
Yes, the issue still stays with actual version.
And in the long ArduMower thread there was a second one with the same behavior. But I do not know who and when it the thread it was.

**Comment by EinEinfach** [comment]
Can you share you log again

Thx

**Comment by SirVival71** [comment]
The issue appears at 10:31:00
[cassandra.log](https://github.com/EinEinfach/CaSSAndRA/files/13175153/cassandra.log)

**Comment by EinEinfach** [comment]
Please in DEBUG Level

**Comment by SirVival71** [comment]
How to do it in actual versions?

**Comment by EinEinfach** [comment]
Just start the app with
./app.py --app_log_level "DEBUG"
to log in debug level to journalctl
or
./app.py --app_file_log_level "DEBUG"
to log in debug level to .cassandra/log directory

**Comment by SirVival71** [comment]
The sent log file is the output I get with
./app.py --app_log_file_level "DEBUG"

The direct output is the same and should be DEBUG by default as you described in the documentation.

**Comment by EinEinfach** [comment]
./app.py --app_log_level "DEBUG"

**Comment by SirVival71** [comment]
OK, I was successful with
./app.py --app_log_level "DEBUG" >output.txt
The default of the direct app output seems to be INFO, not DEFAULT as described.
and --app_log_file_level seems not changing the level in the cassandra.log file

 
[output.txt](https://github.com/EinEinfach/CaSSAndRA/files/13175621/output.txt)

**Comment by EinEinfach** [comment]
Can you share your
pip list
output

**Comment by SirVival71** [comment]
Package                   Version
------------------------- ---------
arandr                    0.1.10
astroid                   2.5.1
asttokens                 2.0.4
automationhat             0.2.0
beautifulsoup4            4.9.3
blinker                   1.6.2
blinkt                    0.1.2
buttonshim                0.0.2
Cap1xxx                   0.1.3
certifi                   2022.12.7
chardet                   4.0.0
charset-normalizer        3.1.0
click                     8.1.3
colorama                  0.4.4
colorzero                 1.1
cryptography              3.3.2
cupshelpers               1.0
dash                      2.9.3
dash-bootstrap-components 1.4.1
dash-core-components      2.0.0
dash-daq                  0.5.0
dash-html-components      2.0.0
dash-table                5.0.0
dbus-python               1.2.16
distro                    1.5.0
docutils                  0.16
drumhat                   0.1.0
envirophat                1.0.0
executing                 2.0.0
ExplorerHAT               0.4.2
Flask                     2.3.1
fourletterphat            0.1.0
gpiozero                  1.6.2
html5lib                  1.1
icecream                  2.1.3
idna                      3.4
importlib-metadata        6.6.0
isort                     5.6.4
itsdangerous              2.1.2
jedi                      0.18.0
Jinja2                    3.1.2
lazy-object-proxy         0.0.0
logilab-common            1.8.1
lxml                      4.6.3
MarkupSafe                2.1.2
mccabe                    0.6.1
microdotphat              0.2.1
mote                      0.0.4
motephat                  0.0.3
mypy                      0.812
mypy-extensions           0.4.3
networkx                  3.1
numpy                     1.24.3
oauthlib                  3.1.0
opencv-python             4.7.0.72
packaging                 23.1
paho-mqtt                 1.6.1
pandas                    2.0.1
pantilthat                0.0.7
parso                     0.8.1
pexpect                   4.8.0
pgzero                    1.2
phatbeat                  0.1.1
pianohat                  0.1.0
picamera2                 0.3.9
pidng                     4.0.9
piexif                    1.1.3
piglow                    1.2.5
pigpio                    1.78
Pillow                    10.0.1
pip                       23.2.1
plotly                    5.14.1
psutil                    5.8.0
pycairo                   1.16.2
pycups                    2.0.1
pygame                    1.9.6
Pygments                  2.7.1
PyGObject                 3.38.0
pyinotify                 0.9.6
PyJWT                     1.7.1
pylint                    2.7.2
PyOpenGL                  3.1.5
pyOpenSSL                 20.0.1
PyQt5                     5.15.2
PyQt5-sip                 12.8.1
pyserial                  3.5
pysmbc                    1.0.23
python-apt                2.2.1
python-dateutil           2.8.2
python-dotenv             1.0.0
python-prctl              1.7
pytz                      2023.3
rainbowhat                0.1.0
reportlab                 3.5.59
requests                  2.31.0
requests-oauthlib         1.0.0
responses                 0.12.1
roman                     2.0.0
RPi.GPIO                  0.7.0
RTIMULib                  7.2.1
scrollphat                0.0.7
scrollphathd              1.2.1
Send2Trash                1.6.0b1
sense-hat                 2.4.0
setuptools                52.0.0
shapely                   2.0.1
simplejpeg                1.6.4
simplejson                3.17.2
six                       1.16.0
skywriter                 0.0.7
sn3218                    1.2.7
soupsieve                 2.2.1
spidev                    3.5
ssh-import-id             5.10
tenacity                  8.2.2
tflite-runtime            2.11.0
thonny                    4.0.1
toml                      0.10.1
touchphat                 0.0.1
twython                   3.8.2
typed-ast                 1.4.2
typing-extensions         3.7.4.3
tzdata                    2023.3
unicornhathd              0.0.4
urllib3                   1.26.15
v4l2-python3              0.3.2
webencodings              0.5.1
Werkzeug                  2.3.0
wheel                     0.34.2
wrapt                     1.12.1
zipp                      3.15.0

**Comment by max951** [comment]
i've a simular (or maybe the same) behavior.

![hc_1269](https://github.com/EinEinfach/CaSSAndRA/assets/12292845/674c292f-506e-4e4e-970c-a528ee8fe494)

I have installed slightly fewer packages. Maybe this info will help you a bit
Package                   Version
------------------------- ---------
asttokens                 2.4.0
blinker                   1.6.2
certifi                   2020.6.20
chardet                   4.0.0
charset-normalizer        3.2.0
click                     8.1.3
colorama                  0.4.6
colorzero                 1.1
dash                      2.9.3
dash-bootstrap-components 1.4.1
dash-core-components      2.0.0
dash-daq                  0.5.0
dash-html-components      2.0.0
dash-table                5.0.0
distro                    1.5.0
executing                 2.0.0
Flask                     2.3.2
gpiozero                  1.6.2
icecream                  2.1.3
idna                      2.10
importlib-metadata        6.8.0
itsdangerous              2.1.2
Jinja2                    3.1.2
MarkupSafe                2.1.3
networkx                  3.1
numpy                     1.24.3
packaging                 23.1
paho-mqtt                 1.6.1
pandas                    2.0.1
picamera2                 0.3.9
pidng                     4.0.9
piexif                    1.1.3
Pillow                    10.0.1
pip                       20.3.4
plotly                    5.14.1
Pygments                  2.16.1
pyserial                  3.5
python-apt                2.2.1
python-dateutil           2.8.2
python-prctl              1.7
pytz                      2023.3
requests                  2.31.0
RPi.GPIO                  0.7.0
setuptools                52.0.0
shapely                   2.0.1
simplejpeg                1.6.4
six                       1.16.0
spidev                    3.5
ssh-import-id             5.10
tenacity                  8.2.2
toml                      0.10.1
tzdata                    2023.3
urllib3                   1.26.5
v4l2-python3              0.3.2
Werkzeug                  2.3.6
wheel                     0.34.2
zipp                      3.16.2

**Comment by EinEinfach** [comment]
I added new branch turn-figure-tests. Pls do the same again and post logfile here.

thanks

**Comment by SirVival71** [comment]
I'm not shure if the output worked as wanted. Additionally to the logfile I got the following output in the console:
./app.py --app_log_level "DEBUG" >output.txt
ic| figure: <POINT (0 0)>
ic| figure_rotated: <POINT (0 0)>
ic| figure: <POLYGON ((4.25 -2.63, 4.76 -2.85, 6.27 -2.96, 7.22 -3.28, 7.67 -3.23, 8.29 ...>
ic| figure: <POLYGON ((4.25 -2.63, 4.76 -2.85, 6.27 -2.96, 7.22 -3.28, 7.67 -3.23, 8.29 ...>
ic| figure: <LINESTRING (3.82 -2.35, 1.88 -4.19, 2.17 -5.18, 6.17 -9.33, 7.2 -8.69, 8.56...>
ic| figure_rotated: <LINESTRING (-0.963 4.38, 1.708 4.263, 2.219 5.159, 2.425 10.919, 1.25 11.21...>

[output.txt](https://github.com/EinEinfach/CaSSAndRA/files/13178153/output.txt)

**Comment by EinEinfach** [comment]
Pls try now

**Comment by SirVival71** [comment]
ic| figure: <POINT (0 0)>
ic| figure.is_valid: True
ic| figure_rotated: <POINT (0 0)>
ic| figure.is_valid: True
ic| figure: <POLYGON ((4.25 -2.63, 4.76 -2.85, 6.27 -2.96, 7.22 -3.28, 7.67 -3.23, 8.29 ...>
ic| figure.is_valid: True
ic| figure: <POLYGON ((4.25 -2.63, 4.76 -2.85, 6.27 -2.96, 7.22 -3.28, 7.67 -3.23, 8.29 ...>
ic| figure.is_valid: True
ic| figure: <LINESTRING (3.82 -2.35, 1.88 -4.19, 2.17 -5.18, 6.17 -9.33, 7.2 -8.69, 8.56...>
ic| figure.is_valid: True
ic| figure_rotated: <LINESTRING (-0.963 4.38, 1.708 4.263, 2.219 5.159, 2.425 10.919, 1.25 11.21...>
ic| figure.is_valid: True

[output.txt](https://github.com/EinEinfach/CaSSAndRA/files/13208751/output.txt)

**Comment by EinEinfach** [comment]
I'm slowly running out of ideas about what that could be. Which Python version are you using?

**Comment by SirVival71** [comment]
I tried several versions. At the past we compared and tried it with the same version.

I just upgraded to the latest delivery of 64bit bullseye. At the moment I use python 3.9.2

**Comment by EinEinfach** [comment]
I checked something new to the test branch. Pls test

**Comment by SirVival71** [comment]
The error message is "Points of LinearRing do not form a closed linestring" But the exclusion is an exactly closed linestring.
Now, I manually manipulated the perimeter file. I moved the endpoint of the exclusion to 1µm distance to the start point of the exclusion.
And you will not believe it: Now, it works as it shall.
I don't know, what the problem in the algorithm is. But I have a solution for me. I will use the manipulated perimeter file in future. So I'm able to mow lines with the planned mow angle.

**Comment by EinEinfach** [comment]
Can you share the log file. With new version just points are rotated, it is very strange that you get this error message

**Comment by SirVival71** [comment]
This way works, too.

ic| figure: <POINT (0 0)>
ic| figure.is_valid: True
ic| figure_rotated: <POINT (0 0)>
ic| figure.is_valid: True
ic| figure: <POLYGON ((4.25 -2.63, 4.76 -2.85, 6.27 -2.96, 7.22 -3.28, 7.67 -3.23, 8.29 ...>
ic| figure.is_valid: True
ic| figure_rotated: <POLYGON ((-5.357 -1.444, -6.485 -2.454, -7.375 -2.915, -7.651 -3.274, -9.67...>
ic| figure.is_valid: True
ic| figure: <LINESTRING (-4.344 -1.115, -4.32 1.558, -5.234 2.037, -10.997 2.043, -11.25...>
ic| figure.is_valid: True
ic| figure_rotated: <LINESTRING (3.82 -2.35, 1.88 -4.19, 2.17 -5.18, 6.17 -9.33, 7.2 -8.69, 8.56...>
ic| figure.is_valid: True

[output.txt](https://github.com/EinEinfach/CaSSAndRA/files/13225561/output.txt)
